package com.aspire.asat.billing.service.serviceImpl;

import com.aspire.asat.billing.dto.*;
import com.aspire.asat.billing.dto.invoice.ProductSelectionDto;
import com.aspire.asat.billing.enums.CouponType;
import com.aspire.asat.billing.exception.BillingServiceException;
import com.aspire.asat.billing.exception.CouponAlreadyExistsException;
import com.aspire.asat.billing.exception.CouponLimitExceededException;
import com.aspire.asat.billing.exception.CouponNotFoundException;
import com.aspire.asat.billing.exception.CouponValidationException;
import com.aspire.asat.billing.exception.UnsupportedCouponTypeException;
import com.aspire.asat.billing.model.Coupon;
import com.aspire.asat.billing.model.Payment;
import com.aspire.asat.billing.model.ProductRestriction;
import com.aspire.asat.billing.repo.CouponRepository;
import com.aspire.asat.billing.repo.customRepo.CouponRepositoryCustom;
import com.aspire.asat.billing.service.CouponService;
import com.aspire.asat.billing.utils.common.QrCodeGenerator;
import com.aspire.asat.billing.utils.file.AzureBlobUploader;
import com.aspire.asat.billing.utils.file.CsvGeneratorUtil;
import com.aspire.asat.common.util.MoneyUtil;
import io.jsonwebtoken.io.IOException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.util.*;
import java.util.stream.Collectors;

@Service
@Slf4j
public class CouponServiceImpl implements CouponService {

    private final CouponRepository couponRepository;
    private final CouponRepositoryCustom couponRepositoryCustom;
    @Autowired
    MongoTemplate mongoTemplate;
    @Autowired
    private AzureBlobUploader azureBlobUploader;

    @Autowired
    private QrCodeGenerator qrCodeGenerator;

    @Autowired
    public CouponServiceImpl(CouponRepository couponRepository, CouponRepositoryCustom couponRepositoryCustom) {
        this.couponRepository = couponRepository;
        this.couponRepositoryCustom = couponRepositoryCustom;
    }

    /**
     * Create a new coupon
     *
     * @author Mahadi Hasan Joy
     * @since 2025-04-15
     */
    @Override
    public CouponCreateResponseDTO createCoupon(CouponCreateRequestDTO couponCreateRequestDTO) {

        if (couponRepository.existsByCode(couponCreateRequestDTO.getCode())) {
            throw new CouponAlreadyExistsException("Coupon code already exists: " + couponCreateRequestDTO.getCode());
        }

        CouponType couponType = CouponType.valueOf(couponCreateRequestDTO.getType().toUpperCase());

        Coupon coupon = new Coupon();
        coupon.setName(couponCreateRequestDTO.getName());
        coupon.setDescription(couponCreateRequestDTO.getDescription());
        coupon.setCode(couponCreateRequestDTO.getCode());
        coupon.setAutoGenerated(couponCreateRequestDTO.isAutoGenerated());
        coupon.setType(couponType);
        coupon.setValue(couponCreateRequestDTO.getValue());
        coupon.setCurrency(couponCreateRequestDTO.getCurrency());
        coupon.setValidFrom(couponCreateRequestDTO.getValidFrom());
        coupon.setValidUntil(couponCreateRequestDTO.getValidUntil());
        coupon.setUsageLimit(couponCreateRequestDTO.getUsageLimit());
        coupon.setTotalUsed(0);
        coupon.setMinPurchaseAmount(couponCreateRequestDTO.getMinPurchaseAmount());
        coupon.setActive(couponCreateRequestDTO.isActive());
        coupon.setStackable(couponCreateRequestDTO.isStackable());
        coupon.setGeographicRestrictions(couponCreateRequestDTO.getGeographicRestrictions());

        // Set productRestrictions: if provided and not empty, map and set; if null or empty, set to null
        if (couponCreateRequestDTO.getProductRestrictions() != null && !couponCreateRequestDTO.getProductRestrictions().isEmpty()) {
            List<ProductRestriction> restrictions = couponCreateRequestDTO.getProductRestrictions().stream().map(this::mapToModel).collect(Collectors.toList());
            coupon.setProductRestrictions(restrictions);
        } else {
            // Allow creating coupon without productRestrictions (null or empty list)
            coupon.setProductRestrictions(null);
        }

        coupon.setCreatedAt(Instant.now());
        coupon.setUpdatedAt(Instant.now());

        Coupon saved = couponRepository.save(coupon);
        return mapToResponse(saved);
    }


    /**
     * Generate a QR code for the coupon and upload it to Azure Blob Storage
     *
     * @param couponCode The coupon code
     * @return CouponQrResponseDTO containing the QR code URL
     * @throws IOException if an error occurs during QR code generation or upload
     * @author Mahadi Hasan Joy
     * @since 2025-04-16
     */
    @Override
    public CouponQrResponseDTO generateCouponQrAndUpload(String couponCode) {
        Coupon coupon = couponRepository.findByCode(couponCode).orElseThrow(() -> new CouponNotFoundException("Coupon not found with code: " + couponCode));

//        if (coupon.getQrCodeUrl() != null && !coupon.getQrCodeUrl().isBlank()) {
//            throw new QrCodeAlreadyGeneratedException("QR code has already been generated for coupon: " + couponCode);
//        }
//        TODO: Implement QR code generation and upload logic and get the URL from settings
        String url = "https://aspirelms.com/checkout" + "?coupon=" + couponCode;

        ByteArrayOutputStream baos = qrCodeGenerator.generateQRCodeStream(url, 300, 300);
        ByteArrayInputStream inputStream = new ByteArrayInputStream(baos.toByteArray());

        String fileName = "coupon_qr_" + couponCode + ".png";

        String fileUrl = azureBlobUploader.uploadFile(fileName, inputStream, baos.size(), "image/png");

        coupon.setQrCodeUrl(fileUrl);
//        TODO: Implement the logic to set the URL in the coupon object
        coupon.setUrlCoupon(url);
        coupon.setUpdatedAt(Instant.now());
        couponRepository.save(coupon);

        return new CouponQrResponseDTO(coupon.getCode(), url, fileUrl);
    }

    /**
     * Get coupon by ID
     *
     * @param id
     * @return
     * @author Mahadi Hasan Joy
     * @since 2025-04-17
     */
    @Override
    public CouponCreateResponseDTO getCouponById(String id) {
        Coupon coupon = couponRepository.findById(id).orElseThrow(() -> new CouponNotFoundException("Coupon not found with ID: " + id));
        log.info("Fetching coupon with ID: {}", id);
        return mapToResponse(coupon);
    }

    /**
     * Get a list of coupons with pagination and filtering
     *
     * @param offset
     * @param limit
     * @param searchParam
     * @param isActive
     * @param isExpired
     * @return
     * @author Mahadi Hasan Joy
     * @since 2025-04-17
     */
    @Override
    public List<CouponCreateResponseDTO> getCoupons(int offset, int limit, String searchParam, Boolean isActive,
            Boolean isExpired, String couponType, String productId, String order) {
        if (limit <= 0) {
            throw new BillingServiceException(
                "Limit must be greater than 0",
                HttpStatus.BAD_REQUEST
            );
        }

        if (offset < 0) {
            throw new BillingServiceException(
                "Offset must be greater than or equal to 0",
                HttpStatus.BAD_REQUEST
            );
        }

        int skip = offset * limit;
        Criteria criteria = buildCouponListCriteria(searchParam, isActive, isExpired, couponType, productId);
        Query query = new Query(criteria)
                .with(Sort.by(resolveCreatedAtSortDirection(order), "createdAt"))
                .skip(skip)
                .limit(limit);
        List<Coupon> couponList = mongoTemplate.find(query, Coupon.class);

        if (couponList.isEmpty()) {
            return List.of();
        }

        return couponList.stream().map(this::mapToResponse).collect(Collectors.toList());
    }


    /**
     * Get the count of coupons based on search parameters
     *
     * @param searchParam
     * @param isActive
     * @param isExpired
     * @return
     * @author Mahadi Hasan Joy
     * @since 2025-04-17
     */
    @Override
    public long getCouponsCount(String searchParam, Boolean isActive, Boolean isExpired, String couponType, String productId) {
        Criteria criteria = buildCouponListCriteria(searchParam, isActive, isExpired, couponType, productId);
        Query query = new Query(criteria);
        return mongoTemplate.count(query, Coupon.class);
    }

    private Criteria buildCouponListCriteria(String searchParam, Boolean isActive, Boolean isExpired,
            String couponType, String productId) {
        Criteria criteria = new Criteria();
        List<Criteria> criteriaList = new ArrayList<>();

        if (searchParam != null && !searchParam.trim().isEmpty()) {
            criteriaList.add(Criteria.where("code").regex(searchParam.trim(), "i"));
        }

        if (isActive != null) {
            criteriaList.add(Criteria.where("isActive").is(isActive));
        }

        if (isExpired != null) {
            Instant now = Instant.now();
            if (isExpired) {
                criteriaList.add(Criteria.where("validUntil").lt(now));
            } else {
                criteriaList.add(Criteria.where("validUntil").gte(now));
            }
        }

        if (couponType != null && !couponType.trim().isEmpty()) {
            try {
                CouponType type = CouponType.valueOf(couponType.trim().toUpperCase());
                criteriaList.add(Criteria.where("type").is(type));
            } catch (IllegalArgumentException e) {
                throw new BillingServiceException(
                    "Invalid coupon type: " + couponType + ". Valid values are: PERCENTAGE, FIXED",
                    HttpStatus.BAD_REQUEST
                );
            }
        }

        if (productId != null && !productId.trim().isEmpty()) {
            criteriaList.add(Criteria.where("productRestrictions.productId").is(productId.trim()));
        }

        if (!criteriaList.isEmpty()) {
            criteria.andOperator(criteriaList.toArray(new Criteria[0]));
        }

        return criteria;
    }

    private Sort.Direction resolveCreatedAtSortDirection(String order) {
        if (order == null || order.isBlank()) {
            return Sort.Direction.ASC;
        }
        return switch (order.trim().toUpperCase()) {
            case "ASC" -> Sort.Direction.ASC;
            case "DESC" -> Sort.Direction.DESC;
            default -> throw new BillingServiceException(
                    "Invalid order: " + order + ". Valid values are: ASC, DESC",
                    HttpStatus.BAD_REQUEST);
        };
    }


    /**
     * Update an existing coupon
     *
     * @param id
     * @param dto
     * @return
     * @author Mahadi Hasan Joy
     * @since 2025-04-17
     */
    @Override
    public CouponCreateResponseDTO updateCoupon(String id, CouponCreateRequestDTO dto) {
        Coupon coupon = couponRepository.findById(id).orElseThrow(() -> new CouponNotFoundException("Coupon not found with ID: " + id));

        // Only update fields if provided in DTO, otherwise keep existing values from repository
        
        // Update name if provided
        if (dto.getName() != null && !dto.getName().isBlank()) {
            coupon.setName(dto.getName());
        }
        
        // Update description if provided
        if (dto.getDescription() != null && !dto.getDescription().isBlank()) {
            coupon.setDescription(dto.getDescription());
        }
        
        // Update code if provided (and check for duplicates)
        if (dto.getCode() != null && !dto.getCode().isBlank()) {
            // Check if another coupon already has the same code
            Optional<Coupon> existingWithSameCode = couponRepository.findByCode(dto.getCode());
            if (existingWithSameCode.isPresent() && !existingWithSameCode.get().getId().equals(id)) {
                throw new CouponAlreadyExistsException("Another coupon already exists with code: " + dto.getCode());
            }
            coupon.setCode(dto.getCode());
        }
        
        // Update autoGenerated if provided (boolean always has a value, so update it)
        coupon.setAutoGenerated(dto.isAutoGenerated());
        
        // Update type if provided
        if (dto.getType() != null && !dto.getType().isBlank()) {
            try {
                coupon.setType(CouponType.valueOf(dto.getType().toUpperCase()));
            } catch (IllegalArgumentException e) {
                throw new UnsupportedCouponTypeException("Invalid coupon type: " + dto.getType());
            }
        }
        
        // Update value if provided
        if (dto.getValue() != null) {
            coupon.setValue(dto.getValue());
        }
        
        // Update currency if provided (can be null to clear it)
        if (dto.getCurrency() != null) {
            coupon.setCurrency(dto.getCurrency());
        }
        
        // Update validFrom if provided
        if (dto.getValidFrom() != null) {
            coupon.setValidFrom(dto.getValidFrom());
        }
        
        // Update validUntil if provided
        if (dto.getValidUntil() != null) {
            coupon.setValidUntil(dto.getValidUntil());
        }
        
        // Update usageLimit if provided
        if (dto.getUsageLimit() != null) {
            coupon.setUsageLimit(dto.getUsageLimit());
        }
        
        // Update minPurchaseAmount if provided (can be null to clear it)
        if (dto.getMinPurchaseAmount() != null) {
            coupon.setMinPurchaseAmount(dto.getMinPurchaseAmount());
        }
        
        // Update isActive (boolean always has a value, so update it)
        coupon.setActive(dto.isActive());
        
        // Update isStackable (boolean always has a value, so update it)
        coupon.setStackable(dto.isStackable());
        
        // Update geographicRestrictions if provided (can be null or empty list)
        if (dto.getGeographicRestrictions() != null) {
            coupon.setGeographicRestrictions(dto.getGeographicRestrictions());
        }
        
        // Update productRestrictions: if provided (even if empty list), update it; if null, keep existing value
        if (dto.getProductRestrictions() != null) {
            // Allow empty list to clear restrictions, or set new restrictions
            List<ProductRestriction> restrictions = dto.getProductRestrictions().isEmpty() 
                ? null 
                : dto.getProductRestrictions().stream().map(this::mapToModel).collect(Collectors.toList());
            coupon.setProductRestrictions(restrictions);
        }
        // If dto.getProductRestrictions() is null, don't change existing productRestrictions (partial update)
        
        coupon.setUpdatedAt(Instant.now());

        return mapToResponse(couponRepository.save(coupon));
    }


    /**
     * Delete a coupon by ID
     *
     * @param id
     * @author Mahadi Hasan Joy
     * @since 2025-04-17
     */
    @Override
    public void deleteCoupon(String id) {
        Coupon coupon = couponRepository.findById(id)
                .orElseThrow(() -> new CouponNotFoundException("Coupon not found with ID: " + id));

        couponRepository.delete(coupon);
    }


    @Override
    public CouponCreateResponseDTO findCouponByCode(String code) {
        return mapToResponse(loadCouponByCode(code));
    }

    /**
     * Get a coupon by its code with availability validation (active, dates, usage limit).
     */
    @Override
    public CouponCreateResponseDTO getCouponByCode(String code) {
        if (code == null || code.trim().isBlank()) {
            throw new CouponValidationException("Coupon code is required");
        }
        code = code.trim();
        Coupon coupon = loadCouponByCode(code);
        validateCouponAvailability(coupon);
        return mapToResponse(coupon);
    }

    private Coupon loadCouponByCode(String code) {
        return couponRepository.findByCode(code)
                .orElseThrow(() -> new CouponNotFoundException("Coupon not found with code: " + code));
    }

    /**
     * Validate a coupon based on various criteria
     *
     * @param dto
     * @return
     * @author Mahadi Hasan Joy
     * @since 2025-04-20
     */
    @Override
    public CouponCreateResponseDTO validateCoupon(ValidateCouponRequestDTO dto) {
        if ((dto.getCouponId() == null || dto.getCouponId().isBlank()) &&
                (dto.getCouponCode() == null || dto.getCouponCode().isBlank())) {
            throw new CouponValidationException("Either coupon ID or coupon code must be provided.");
        }

        if (dto.getAmount() == null) {
            throw new CouponValidationException("Amount is required for validation.");
        }

        String code = dto.getCouponCode();
        if (code == null || code.isBlank()) {
            Coupon coupon = couponRepository.findById(dto.getCouponId())
                    .orElseThrow(() -> new CouponNotFoundException("Coupon not found with ID: " + dto.getCouponId()));
            code = coupon.getCode();
        }

        return validateForRedemption(
                code,
                dto.getAmount(),
                dto.getPackageItems(),
                dto.getClientCountryId()
        );
    }

    @Override
    public CouponCreateResponseDTO validateForRedemption(String couponCode, double amount,
            List<ProductSelectionDto> packageItems, String clientCountryId) {
        Coupon coupon = loadCouponByCode(couponCode);
        validateCouponForRedemption(coupon, amount, packageItems, clientCountryId);
        return mapToResponse(coupon);
    }

    @Override
    public void reserveCouponUsage(String couponId) {
        couponRepositoryCustom.incrementUsageIfBelowLimit(couponId)
                .orElseThrow(() -> new CouponLimitExceededException(
                        "Coupon usage limit has been reached for coupon ID: " + couponId));
    }

    @Override
    public void releaseCouponUsage(String couponId) {
        if (couponId == null || couponId.isBlank()) {
            return;
        }
        Optional<Coupon> released = couponRepositoryCustom.decrementUsageIfAboveZero(couponId);
        if (released.isEmpty()) {
            log.warn("Coupon usage release skipped: totalUsed already 0 for coupon ID: {}", couponId);
        }
    }

    private void validateCouponAvailability(Coupon coupon) {
        if (!coupon.isActive()) {
            throw new CouponValidationException("Coupon is not active.");
        }

        Instant now = Instant.now();
        if (coupon.getValidFrom() != null && coupon.getValidFrom().isAfter(now)) {
            throw new CouponValidationException(
                    String.format("Coupon is not yet valid. Valid from: %s. Current time: %s",
                            coupon.getValidFrom(), now));
        }

        if (coupon.getValidUntil() != null && coupon.getValidUntil().isBefore(now)) {
            throw new CouponValidationException(
                    String.format("%s Coupon has expired", coupon.getCode()));
        }

        int used = coupon.getTotalUsed() != null ? coupon.getTotalUsed() : 0;
        if (coupon.getUsageLimit() != null && used >= coupon.getUsageLimit()) {
            throw new CouponValidationException("Coupon usage limit has been reached.");
        }
    }

    private void validateCouponForRedemption(Coupon coupon, double amount,
            List<ProductSelectionDto> packageItems, String clientCountryId) {
        validateCouponAvailability(coupon);

        if (coupon.getMinPurchaseAmount() != null && amount < coupon.getMinPurchaseAmount()) {
            throw new CouponValidationException("Minimum purchase amount not met for this coupon.");
        }

        if (coupon.getGeographicRestrictions() != null && !coupon.getGeographicRestrictions().isEmpty()) {
            if (clientCountryId == null || !coupon.getGeographicRestrictions().contains(clientCountryId)) {
                throw new CouponValidationException("Coupon is not valid in your region.");
            }
            return;
        }

        if (packageItems != null && !packageItems.isEmpty()
                && coupon.getProductRestrictions() != null && !coupon.getProductRestrictions().isEmpty()) {
            boolean anyMatch = coupon.getProductRestrictions().stream()
                    .anyMatch(restriction -> packageItems.stream()
                            .anyMatch(pkg -> {
                                boolean productMatch = pkg.getProductId().equals(restriction.getProductId());
                                if (restriction.getPackageId() == null || restriction.getPackageId().isBlank()) {
                                    return productMatch;
                                }
                                return productMatch
                                        && pkg.getPackageId() != null
                                        && pkg.getPackageId().equals(restriction.getPackageId());
                            }));

            if (!anyMatch) {
                throw new CouponValidationException("Coupon is not valid for any of the selected products/packages.");
            }
        }
    }

    /**
     * Calculate the discount based on the coupon and package items
     * 
     * @param packageItems List of product selections
     * @param clientCountryId Client country ID (UUID format)
     * @param coupon Coupon to apply
     * @return CouponDiscountResponseDTO
     * @author Mahadi Hasan Joy
     * @since 2025-04-20
     */
    @Override
    public CouponDiscountResponseDTO calculateCouponDiscount(List<ProductSelectionDto> packageItems, String clientCountryId, CouponCreateResponseDTO coupon) {
        if (packageItems == null || coupon == null) {
            throw new IllegalArgumentException("Package items and coupon are required for discount calculation.");
        }

        boolean applyDiscountToAll = false;

        if (coupon.getGeographicRestrictions() != null && !coupon.getGeographicRestrictions().isEmpty()) {
            if (clientCountryId != null && coupon.getGeographicRestrictions().contains(clientCountryId)) {
                applyDiscountToAll = true;
            }
        }

        List<String> eligibleProductIds = coupon.getProductRestrictions() != null
                ? coupon.getProductRestrictions().stream().map(ProductRestrictionDTO::getProductId).collect(Collectors.toList())
                : null;

        if (!applyDiscountToAll && (eligibleProductIds == null || eligibleProductIds.isEmpty()) &&
                (coupon.getGeographicRestrictions() == null || coupon.getGeographicRestrictions().isEmpty())) {
            applyDiscountToAll = true;
        }

        double actualTotal = 0.0;
        double totalDiscount = 0.0;
        List<DiscountedItemDTO> breakdown = new ArrayList<>();

        for (ProductSelectionDto item : packageItems) {
            double original = MoneyUtil.round(item.getLicenseCount() * item.getPricePerLicense() * item.getValidityPeriod());
            double discounted = original;
            boolean applied = false;

            // Check eligibility: must match a product/package restriction (same rules as validateForRedemption)
            boolean isEligible = false;
            if (applyDiscountToAll) {
                isEligible = true;
            } else if (coupon.getProductRestrictions() != null && !coupon.getProductRestrictions().isEmpty()) {
                isEligible = coupon.getProductRestrictions().stream()
                        .anyMatch(restriction -> lineItemMatchesProductRestriction(item, restriction));
            }

            if (isEligible) {
                if ("PERCENTAGE".equalsIgnoreCase(coupon.getType())) {
                    discounted = MoneyUtil.round(original - (original * coupon.getValue() / 100.0));
                } else if ("FIXED".equalsIgnoreCase(coupon.getType())) {
                    discounted = MoneyUtil.round(Math.max(0, original - coupon.getValue()));
                }
                totalDiscount = MoneyUtil.round(totalDiscount + (original - discounted));
                applied = true;
            }

            actualTotal = MoneyUtil.round(actualTotal + original);
            breakdown.add(new DiscountedItemDTO(item.getProductId(), original, discounted, applied));
        }

        double subtotal = MoneyUtil.round(actualTotal - totalDiscount);

        return new CouponDiscountResponseDTO(
                actualTotal,
                totalDiscount,
                subtotal,
                0.0,               // VAT excluded
                subtotal,          // Grand total equals subtotal
                breakdown
        );
    }

    private boolean lineItemMatchesProductRestriction(ProductSelectionDto item, ProductRestrictionDTO restriction) {
        if (restriction.getProductId() == null || !restriction.getProductId().equals(item.getProductId())) {
            return false;
        }
        if (restriction.getPackageId() == null || restriction.getPackageId().isBlank()) {
            return true;
        }
        return restriction.getPackageId().equals(item.getPackageId());
    }



    /**
     * @deprecated Use calculateCouponDiscount(List, String, CouponCreateResponseDTO) instead.
     * This method throws UnsupportedOperationException as PaymentRequestDTO no longer contains packageItems.
     */
    @Override
    @Deprecated
    public CouponDiscountResponseDTO calculateCouponDiscount(PaymentRequestDTO paymentRequestDTO, CouponCreateResponseDTO coupon) {
        throw new UnsupportedOperationException(
                "calculateCouponDiscount(PaymentRequestDTO, CouponCreateResponseDTO) is deprecated. " +
                "Use calculateCouponDiscount(List<ProductSelectionDto>, String, CouponCreateResponseDTO) instead. " +
                "PaymentRequestDTO no longer contains packageItems or clientRegion.");
    }

    /**
     * @deprecated Use calculateNormalBill(List) instead.
     * This method throws UnsupportedOperationException as PaymentRequestDTO no longer contains packageItems.
     */
    @Override
    @Deprecated
    public CouponDiscountResponseDTO calculateNormalBill(PaymentRequestDTO paymentRequestDTO) {
        throw new UnsupportedOperationException(
                "calculateNormalBill(PaymentRequestDTO) is deprecated. " +
                "Use calculateNormalBill(List<ProductSelectionDto>) instead. " +
                "PaymentRequestDTO no longer contains packageItems.");
    }

    /**
     * Calculate the normal bill without any coupon
     *
     * @param packageItems List of product selections
     * @return CouponDiscountResponseDTO
     * @author Mahadi Hasan Joy
     * @since 2025-04-20
     */
    @Override
    public CouponDiscountResponseDTO calculateNormalBill(List<ProductSelectionDto> packageItems) {
        if (packageItems == null || packageItems.isEmpty()) {
            throw new IllegalArgumentException("Package items are required for bill calculation.");
        }

        double actualTotal = 0.0;
        double totalDiscount = 0.0;
        List<DiscountedItemDTO> breakdown = new ArrayList<>();

        for (ProductSelectionDto item : packageItems) {
            double price = MoneyUtil.round(item.getPricePerLicense() * item.getLicenseCount() * item.getValidityPeriod());
            actualTotal = MoneyUtil.round(actualTotal + price);

            // No coupon: original == discounted, no discount applied
            breakdown.add(new DiscountedItemDTO(item.getProductId(), price, price, false));
        }

        double subtotal = actualTotal;

        return new CouponDiscountResponseDTO(
                actualTotal,
                totalDiscount,
                subtotal,
                0.0,            // VAT excluded from here
                subtotal,       // Grand total same as subtotal (no VAT included)
                breakdown
        );
    }


    private ProductRestriction mapToModel(ProductRestrictionDTO dto) {
        ProductRestriction restriction = new ProductRestriction();
        restriction.setProductId(dto.getProductId());
        restriction.setProductName(dto.getProductName());
        restriction.setPackageId(dto.getPackageId());
        restriction.setPackageName(dto.getPackageName());
        return restriction;
    }

    private CouponCreateResponseDTO mapToResponse(Coupon coupon) {
        CouponCreateResponseDTO response = new CouponCreateResponseDTO();
        response.setId(coupon.getId());
        response.setName(coupon.getName());
        response.setDescription(coupon.getDescription());
        response.setCode(coupon.getCode());
        response.setAutoGenerated(coupon.isAutoGenerated());
        response.setType(coupon.getType().toString());
        response.setValue(coupon.getValue());
        response.setCurrency(coupon.getCurrency());
        response.setValidFrom(coupon.getValidFrom());
        response.setValidUntil(coupon.getValidUntil());
        response.setUsageLimit(coupon.getUsageLimit());
        response.setTotalUsed(coupon.getTotalUsed());
        response.setMinPurchaseAmount(coupon.getMinPurchaseAmount());
        response.setActive(coupon.isActive());
        response.setStackable(coupon.isStackable());
        response.setGeographicRestrictions(coupon.getGeographicRestrictions());

        if (coupon.getProductRestrictions() != null) {
            List<ProductRestrictionDTO> dtoList = coupon.getProductRestrictions().stream().map(this::mapToProductRestrictionDTO).collect(Collectors.toList());
            response.setProductRestrictions(dtoList);
        }

        response.setQrCodeUrl(coupon.getQrCodeUrl());
        response.setUrlCoupon(coupon.getUrlCoupon());
        response.setCreatedBy(coupon.getCreatedBy());
        response.setCreatedAt(coupon.getCreatedAt());
        response.setUpdatedAt(coupon.getUpdatedAt());

        return response;
    }

    private ProductRestrictionDTO mapToProductRestrictionDTO(ProductRestriction restriction) {
        ProductRestrictionDTO dto = new ProductRestrictionDTO();
        dto.setProductId(restriction.getProductId());
        dto.setProductName(restriction.getProductName());
        dto.setPackageId(restriction.getPackageId());
        dto.setPackageName(restriction.getPackageName());
        return dto;
    }

    @Override
    public byte[] exportCouponsCsv(String searchParam, Boolean isActive, Boolean isExpired, String couponType, String productId) {
        log.info("Exporting coupons to CSV with filters - searchParam: {}, isActive: {}, isExpired: {}, couponType: {}, productId: {}", 
                searchParam, isActive, isExpired, couponType, productId);

        Criteria criteria = buildCouponListCriteria(searchParam, isActive, isExpired, couponType, productId);

        Query query = new Query(criteria);
        List<Coupon> couponList = mongoTemplate.find(query, Coupon.class);

        if (couponList.isEmpty()) {
            throw new CouponNotFoundException("No coupons found matching the criteria");
        }

        // Convert to DTOs
        List<CouponCreateResponseDTO> couponDTOs = couponList.stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());

        // Generate CSV
        ByteArrayOutputStream csvOutput = CsvGeneratorUtil.generateCouponListCsv(couponDTOs);
        return csvOutput.toByteArray();
    }

    @Override
    public CouponDashboardResponseDTO getCouponDashboard() {
        log.info("Fetching coupon dashboard statistics");

        // Calculate total coupons
        long totalCoupons = couponRepository.count();

        // Calculate active coupons
        Query activeQuery = new Query(Criteria.where("isActive").is(true));
        long activeCoupons = mongoTemplate.count(activeQuery, Coupon.class);

        // Calculate inactive coupons
        Query inactiveQuery = new Query(Criteria.where("isActive").is(false));
        long inactiveCoupons = mongoTemplate.count(inactiveQuery, Coupon.class);

        // Calculate total usage - sum of totalUsed from all coupons
        List<Coupon> allCoupons = couponRepository.findAll();
        long totalUsage = allCoupons.stream()
                .mapToLong(coupon -> coupon.getTotalUsed() != null ? coupon.getTotalUsed() : 0L)
                .sum();

        // Calculate estimated savings - sum of discountAmount from successful payments with coupons
        Query paymentQuery = new Query(Criteria.where("couponId").ne(null)
                .and("status").is("SUCCESS")
                .and("discountAmount").ne(null));
        List<Payment> paymentsWithCoupons = mongoTemplate.find(paymentQuery, Payment.class);
        double estimatedSavings = paymentsWithCoupons.stream()
                .mapToDouble(payment -> payment.getDiscountAmount() != null ? payment.getDiscountAmount() : 0.0)
                .sum();

        return CouponDashboardResponseDTO.builder()
                .totalCoupons(totalCoupons)
                .activeCoupons(activeCoupons)
                .inactiveCoupons(inactiveCoupons)
                .totalUsage(totalUsage)
                .estimatedSavings(estimatedSavings)
                .build();
    }

}
