plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'application'
}

application {
    mainClass = 'com.aspire.asat.cms.CmsApplication'
}

group 'com.aspire.asat.cms'

dependencies {

    implementation project(':services:cms:api')
    implementation project(':services:cms:core')
    implementation project(':common:core')                   // ✅ not ':common'
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.0.6'
    implementation project.rootProject.ext.libraries.development.springDocUi
    implementation project.rootProject.ext.libraries.core.springBootStarter
    implementation project.rootProject.ext.libraries.core.springBootStarterWeb
    implementation project.rootProject.ext.libraries.core.springBootStarterDataMongo
    implementation project.rootProject.ext.libraries.core.jacksonDatatype
    implementation "com.amazonaws:aws-java-sdk-cloudfront:1.12.777"
    implementation project.rootProject.ext.libraries.core.awsSdkS3


    testImplementation platform(project.rootProject.ext.libraries.test.junitBom)
    testImplementation project.rootProject.ext.libraries.test.junitJupiter

}

tasks.test {
    useJUnitPlatform()
}

tasks.bootJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
