import z from 'zod';

export const couponSchema = z
  .object({
    name: z
      .string()
      .min(1, 'Name is required')
      .max(100, 'Name must be less than 100 characters'),
    description: z
      .string()
      .min(1, 'Description is required')
      .max(500, 'Description must be less than 500 characters'),
    code: z
      .string()
      .min(1, 'Code is required')
      .max(50, 'Code must be less than 50 characters')
      .regex(
        /^[A-Z0-9]+$/,
        'Code must contain only uppercase letters and numbers, no spaces',
      )
      .refine(val => !val.includes(' '), 'Code cannot contain spaces'),
    type: z.string().min(1, 'Type is required'),
    value: z.number().min(1, 'Value must be greater than 0'),
    validFrom: z.string().min(1, 'Valid from date is required'),
    validUntil: z.string().min(1, 'Valid until date is required'),
    usageLimit: z.number().min(1, 'Usage limit must be greater than 0'),
    minPurchaseAmount: z
      .number()
      .min(1, 'Minimum purchase amount must be greater than 0'),
    currency: z.string().optional(),
    autoGenerated: z.boolean(),
    isActive: z.string(),
    isStackable: z.boolean(),
    productRestrictions: z.array(
      z.object({
        productId: z.string(),
        productName: z.string(),
        packageId: z.string(),
        packageName: z.string(),
      }),
    ),
    geographicRestrictions: z.array(z.string()),
  })
  .refine(
    data => {
      const now = truncateToMinute(new Date());
      const validUntil = truncateToMinute(new Date(data.validUntil));
      return validUntil >= now;
    },
    {
      message: 'Valid until date cannot be in the past',
      path: ['validUntil'],
    },
  )
  .refine(
    data => {
      const validFrom = truncateToMinute(new Date(data.validFrom));
      const validUntil = truncateToMinute(new Date(data.validUntil));
      return validUntil > validFrom;
    },
    {
      message: 'Valid until date must be after valid from date',
      path: ['validUntil'],
    },
  );

export type CouponFormData = z.infer<typeof couponSchema>;

const truncateToMinute = (date: Date) => {
  const newDate = new Date(date);
  newDate.setSeconds(0, 0);
  return newDate;
};
