package com.aspire.asat.registration.data.coupon;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

/**
 * DTO for coupon response from billing service
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CouponResponseDTO {

    private String id;
    private String name;
    private String description;
    private String code;
    private boolean autoGenerated;
    private String type; // "PERCENTAGE" or "FIXED"
    private Double value;
    private String currency;
    private Date validFrom;
    private Date validUntil;
    private Integer usageLimit;
    private Integer totalUsed;
    private Double minPurchaseAmount;
    private boolean isActive;
    private boolean isStackable;
    private List<ProductRestrictionDTO> productRestrictions;
    private List<String> geographicRestrictions;
    private String qrCodeUrl;
    private String urlCoupon;
    private String createdBy;
    private Date createdAt;
    private Date updatedAt;
}

