package com.aspire.asat.billing.model;

import com.aspire.asat.billing.enums.CouponType;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.List;

@Data
@Document(collection = "coupons")
public class Coupon {

    @Id
    private String id; // MongoDB ObjectId or custom UUID

    private String name;
    private String description;

    private String code;                    // Unique coupon code
    private boolean autoGenerated;          // Whether system generated the code

    private CouponType type;                // "PERCENTAGE" or "FIXED"
    private Double value;                   // 20.0 for 20% or fixed amount
    private String currency;                // Currency for fixed amount coupons; null if PERCENTAGE

    private Instant validFrom;
    private Instant validUntil;

    private Integer usageLimit;             // Total allowed redemptions (required)
    private Integer totalUsed;              // Number of times coupon has been used (starts at 0)

    private Double minPurchaseAmount;       // Minimum order value

    private boolean isActive;               // Toggle coupon status
    private boolean isStackable;            // Can it be used with other coupons?

    private List<ProductRestriction> productRestrictions; // Course/bundle/etc restrictions
    private List<String> geographicRestrictions;          // Country IDs (UUIDs) for geographic restrictions

    private String qrCodeUrl;               // Generated QR image URL (optional)
    private String urlCoupon;               // URL that applies the coupon (optional)

    private String createdBy;               // Admin or system who created the coupon
    private Instant createdAt;                 // Timestamp of creation
    private Instant updatedAt;                 // Timestamp of last update
}
