export const API_END_POINTS = {
  SUMMARY_DATA: '/billing/api/v1/payment/history/summary',
  COUPON_SUMMARY: '/billing/api/v1/coupon/dashboard',
  COUPON_LIST: '/billing/api/v1/coupon/list?',
  COUPON_EXPORT_CSV: '/billing/api/v1/coupon/export/csv?',
  GET_COUPON_BY_CODE: '/billing/api/v1/coupon/code/:code',
  GET_COUPON_BY_ID: '/billing/api/v1/coupon/id/:id',
  COUPON_CREATE: '/billing/api/v1/coupon/create',
  COUPON_UPDATE: '/billing/api/v1/coupon/update/',
  COUPON_DELETE: '/billing/api/v1/coupon/delete/',
  COUPON_GENERATE_QR_CODE: '/billing/api/v1/coupon/',
  ENABLED_PRODUCT_LIST: '/cms/api/v1/products/enabled?',
  PRODUCT_LIST: '/cms/api/v1/products?',
  INVOICE_LIST: '/billing/api/v1/invoice/list?',
  INVOICE_DETAILS: '/billing/api/v1/invoice/id/',
  APPLY_COUPON: '/billing/api/v1/invoice/:invoiceId/apply-coupon',
  APPLY_DISCOUNT: '/billing/api/v1/invoice/:invoiceId/apply-discount',
  DOWNLOAD_INVOICE_PDF: '/billing/api/v1/invoice/download/:id',
  ONLINE_PAYMENT: '/billing/api/v1/payment/online-entry',
  MANUAL_PAYMENT: '/billing/api/v1/payment/manual-entry',
  PAYMENT_HISTORY: '/billing/api/v1/payment/history?',
  PAYMENT_HISTORY_DETAILS: '/billing/api/v1/payment/details/',
  PAYMENT_HISTORY_EXPORT: '/billing/api/v1/payment/history/download',
  PAYMENT_HISTORY_EXPORT_CSV: '/billing/api/v1/payment/history/export/csv?',
  PENDING_PAYMENT_EXPORT_CSV: '/billing/api/v1/invoice/history/export/csv?',
  CREDIT_DETAILS: '/billing/api/v1/credit/client/',
  CREDIT_TRANSACTION_LIST: '/billing/api/v1/credit/transaction/client/',
  CREDIT_STATUS_UPDATE: '/billing/api/v1/credit/switch-mode/',
  CREDIT_TRANSFER: '/billing/api/v1/credit/transfer',
  CREDIT_DEPOSIT: '/billing/api/v1/credit/deposit',
  CREDIT_WITHDRAW: '/billing/api/v1/credit/withdraw',
  CREDIT_UPDATE: '/billing/api/v1/credit/update/',
  CREDIT_USE_HISTORY: '/billing/api/v1/credit/transaction/usage-list/',
  CREDIT_USER_SUMMARY: '/billing/api/v1/credit/transaction/usage-summary/',
  VAT_LIST: '/billing/api/v1/vat/all?',
  VAT_CREATE: '/billing/api/v1/vat/create',
  VAT_UPDATE: '/billing/api/v1/vat/update/',
  VAT_DELETE: '/billing/api/v1/vat/delete/',
  VAT_DETAILS: '/billing/api/v1/vat/country/',
  COUNTRY_LIST: '/registration/api/v1/dropdown/countries/active',
  STATE_LIST_BY_COUNTRY:
    '/registration/api/v1/dropdown/states/country/:countryId/active',
  MSP_LIST: '/registration/api/v1/msp?',
  MSP_LIST_WITH_FILTERS: '/registration/api/v1/msp/list?',
  MSP_ACTIVE_LICENSE_SUMMARY: '/registration/api/v1/msp/active-license-summary',
  MSP_TIER_LIST: '/registration/api/tier?',
  TIER_LIST: '/registration/api/tier?',
  TIER_CREATE: '/registration/api/tier',
  TIER_UPDATE: '/registration/api/tier/',
  TIER_DELETE: '/registration/api/tier/delete/',
  TIER_DETAILS: '/registration/api/tier/',
  CLIENT_LIST: '/registration/api/v1/client/admin/list?',
  CLIENT_ADMIN_ASSIGN_PRODUCT_LIST:
    '/registration/api/v1/client/admin/products/assigned/:clientAdminId?',
  CLIENT_ADMIN_PENDING_AND_ACTIVE_PRODUCT_LIST:
    '/registration/api/v1/client/admin/products/assigned/active-pending/:clientAdminId?',
  ASPIRE_BILLING_ANALYTICS: '/billing/api/v1/analytics',
  ASPIRE_BILLING_ANALYTICS_EXPORT_CSV: '/billing/api/v1/analytics/export/csv',
  ASPIRE_BILLING_ANALYTICS_EXPORT_PDF: '/billing/api/v1/analytics/export/pdf',

  GET_COMMENTS: '/billing/api/v1/invoice/comment-log/invoice/:invoiceId',
  GET_ACTION_TAKEN_OPTIONS: '/billing/api/v1/invoice/action',
  GET_NEXT_STEP_OPTIONS: '/billing/api/v1/invoice/next-step',
  CREATE_COMMENT: '/billing/api/v1/invoice/comment-log',
  SEND_INVOICE_EMAIL: '/billing/api/v1/invoice/send-email/:id',
  UPDATE_INVOICE_PAYMENT: '/billing/api/v1/invoice/update-payment/:id',
  BILLING_ACTION_LIST: '/billing/api/v1/invoice/action',
  BILLING_NEXT_STEP_LIST: '/billing/api/v1/invoice/next-step',
};
