plugins {
    id 'io.spring.dependency-management' version '1.1.5'
    id 'java'
}
group = 'org.example'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation "software.amazon.awssdk:cloudfront:2.32.28"   // or latest version

    // AWS SDK v2 S3 if you also use S3
    implementation "software.amazon.awssdk:s3:2.32.28"
    
    // AWS SDK v2 SSM and KMS for parameter store and encryption
    implementation project.rootProject.ext.libraries.core.awsSdkSsm
    implementation project.rootProject.ext.libraries.core.awsSdkKms
    implementation project.rootProject.ext.libraries.core.lombok
    implementation project.rootProject.ext.libraries.core.springBootStarterWeb
    implementation 'org.yaml:snakeyaml:2.2'
    implementation project.rootProject.ext.libraries.core.validationApi
    implementation project.rootProject.ext.libraries.core.starterValidation
    annotationProcessor project.rootProject.ext.libraries.core.lombok
    implementation project.rootProject.ext.libraries.core.blobStorage
    implementation project.rootProject.ext.libraries.core.gcpStorage
    implementation project.rootProject.ext.libraries.development.springDocUi

    // PDF generation dependencies
    implementation("com.openhtmltopdf:openhtmltopdf-pdfbox:1.0.10")
    implementation("org.jsoup:jsoup:1.22.1")
    
    // Dependencies for activity logging
    implementation project.rootProject.ext.libraries.core.starterAop
    implementation project.rootProject.ext.libraries.core.aspectjweaver
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.0.6'

    testImplementation platform(project.rootProject.ext.libraries.test.junitBom)
    testImplementation project.rootProject.ext.libraries.test.junitJupiter
}

test {
    useJUnitPlatform()
}