apiVersion : apps/v1
kind: Deployment
metadata:
  name: asat-vps
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asat-vps
  template:
    metadata:
      labels:
        app: asat-vps
#        version: "{{ .VERSION }}"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - vps
      # This toleration allows the pods to be scheduled on nodes with the taint "workload-type: cms".
      tolerations:
        - key: "workload-type"
          operator: "Equal"
          value: "vps"
          effect: "NoSchedule"
      containers:
        - name: asat-vps
#         image: 636499496141.dkr.ecr.us-east-1.amazonaws.com/aspire-vps-asatv2:latest
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 5052
          resources:
            # 'requests' are the minimum resources guaranteed to your pod by Kubernetes.
            requests:
              memory: "1Gi"   # 256 Mebibytes - A common minimum for a Spring Boot app to start.
              cpu: "1"       # 250 millicores (0.25 CPU) - Enough for an idle service.
            # 'limits' are the maximum resources your pod is allowed to use.
            limits:
              memory: "2Gi"   # Prevents the app from consuming too much memory.
              cpu: "2"       # Allows the app to burst up to 0.5 CPU during request processing
