import { zodResolver } from '@hookform/resolvers/zod';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';

import { Button } from 'common/Button';
import { Card, CardDescription, CardTitle } from 'common/Card';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from 'common/Dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from 'common/Form';
import { Input } from 'common/Input';
import { Label } from 'common/Label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from 'common/Select';
import { Textarea } from 'common/Textarea';
import CustomSelect from 'components/CustomSelect';
import SearchSelect from 'components/SearchSelect';
import { useAPI } from 'hooks/UseAPI';
import { ISelectOption } from 'models/Input';
import { IList, IResponse } from 'models/Global';
import { Plus, Trash2 } from 'lucide-react';
import { toast } from 'react-toastify';
import { API_END_POINTS } from 'routes/APIEndpoints';
import { TMultiValue, TSingleValue } from 'models/Input';
import { CouponFormData, couponSchema } from 'schemas/couponSchema';
import { ICoupon } from 'models/Coupon';
import { isSuccessResponse } from 'utils/Helper';

interface ProductPackagePair {
  id: string;
  productId: string;
  packageIds: string[];
  productName: string;
}

interface IPackage {
  id: string;
  packageName: string;
  productId: string;
  featureIds: string[];
  price: number;
  packageStatus: string;
  basePackageId: string;
}

interface IProductWithPackages {
  productId: string;
  productName: string;
  productStatus: string;
  packages: IPackage[];
}

interface IProps {
  isOpen: boolean;
  onClose: () => void;
  coupon?: ICoupon | null;
  onSave: () => void;
}

/** Parse API date string as UTC and return "YYYY-MM-DDTHH:mm" for datetime-local. */
function toUTCDateTimeLocal(isoOrDate: string): string {
  if (!isoOrDate) return '';

  const date = new Date(isoOrDate);

  const localDate = new Date(
    date.getTime() - date.getTimezoneOffset() * 60 * 1000
  );

  return localDate.toISOString().slice(0, 16);
}

/** Convert local date to UTC ISO string for backend. */
function convertToUTC(localDate?: string): string {
  if (!localDate) return '';
  return new Date(localDate).toISOString();
}

const CouponModal = ({ isOpen, onClose, coupon, onSave }: IProps) => {
  const [loading, setLoading] = useState(false);

  // Product-Package pairs state
  const [productPackagePairs, setProductPackagePairs] = useState<
    ProductPackagePair[]
  >([{ id: '1', productId: '', packageIds: [], productName: '' }]);

  // Product and package options state
  const [productOptions, setProductOptions] = useState<Array<ISelectOption>>(
    [],
  );
  const [packageOptionsByProduct, setPackageOptionsByProduct] = useState<
    Record<string, Array<ISelectOption>>
  >({});
  const [productData, setProductData] = useState<IProductWithPackages[]>([]);

  const apiClient = useAPI();

  const form = useForm<CouponFormData>({
    resolver: zodResolver(couponSchema),
    mode: 'onChange',
    defaultValues: {
      name: '',
      description: '',
      code: '',
      type: 'PERCENTAGE',
      value: 0,
      validFrom: '',
      validUntil: '',
      usageLimit: 0,
      minPurchaseAmount: 0,
      currency: 'USD',
      autoGenerated: false,
      isActive: 'true',
      isStackable: false,
      productRestrictions: [],
      geographicRestrictions: [],
    },
  });

  useEffect(() => {
    if (coupon) {
      form.reset({
        name: coupon.name ?? '',
        description: coupon.description ?? '',
        code: coupon.code ?? '',
        type: coupon.type ?? 'PERCENTAGE',
        value: coupon.value ?? 0,
        validFrom: toUTCDateTimeLocal(coupon.validFrom),
        validUntil: toUTCDateTimeLocal(coupon.validUntil),
        usageLimit: coupon.usageLimit ?? 0,
        minPurchaseAmount: coupon.minPurchaseAmount ?? 0,
        currency: coupon.currency ?? 'USD',
        autoGenerated: coupon.autoGenerated ?? false,
        isActive: String(coupon.active ?? false),
        isStackable: coupon.isStackable ?? false,
        productRestrictions: coupon.productRestrictions ?? [],
        geographicRestrictions: coupon.geographicRestrictions ?? [],
      });
    } else {
      form.reset();
    }
  }, [coupon, form]);

  useEffect(() => {
    if (isOpen) {
      fetchProductList();
    }
  }, [isOpen]);

  const fetchProductList = async () => {
    try {
      const response: IResponse<IList<IProductWithPackages>> =
        await apiClient.get(
          API_END_POINTS.ENABLED_PRODUCT_LIST + 'pageSize=1000',
        );

      if (response.statusCode === 200 && response.data?.items) {
        const products = response.data.items;
        setProductData(products);

        // Create product options
        const productOptions = products.map(
          (product: IProductWithPackages) => ({
            id: product.productId,
            label: product.productName,
            value: product.productId,
          }),
        );
        setProductOptions(productOptions);

        // Create package options grouped by product
        const packagesByProduct: Record<string, Array<ISelectOption>> = {};
        products.forEach((product: IProductWithPackages) => {
          packagesByProduct[product.productId] = product.packages
            .filter(pkg => pkg.packageStatus === 'ENABLED') // Only enabled packages
            .map((pkg: IPackage) => ({
              id: pkg.id,
              label: pkg.packageName,
              value: pkg.id,
            }));
        });

        setPackageOptionsByProduct(packagesByProduct);

      } else {
        console.error('Invalid product data response:', response);
        toast.error('Error loading product data');
      }
    } catch (error) {
      console.error('Error fetching Product data:', error);
      toast.error('Error loading Product details');
    }
  };

  // Initialize product-package pairs from coupon data
  useEffect(() => {
    if (
      coupon &&
      coupon.productRestrictions &&
      coupon.productRestrictions.length > 0
    ) {
      // Group restrictions by productId
      const productMap = new Map<string, ProductPackagePair>();

      coupon.productRestrictions.forEach((restriction: any) => {
        const productId = restriction.productId || '';
        if (!productMap.has(productId)) {
          productMap.set(productId, {
            id: Date.now().toString() + Math.random(),
            productId: productId,
            packageIds: [],
            productName: restriction.productName || '',
          });
        }
        const pair = productMap.get(productId)!;
        if (restriction.packageId) {
          pair.packageIds.push(restriction.packageId);
        }
      });

      setProductPackagePairs(Array.from(productMap.values()));
    } else if (!coupon) {
      // Reset to default for new coupon
      setProductPackagePairs([
        { id: '1', productId: '', packageIds: [], productName: '' },
      ]);
    }
  }, [coupon]);

  // Sync form value with productPackagePairs
  useEffect(() => {
    const validPairs = productPackagePairs.filter(
      pair => pair.productId && pair.packageIds.length > 0,
    );

    // Expand pairs into individual entries for each package
    const formValue: Array<{
      productId: string;
      productName: string;
      packageId: string;
      packageName: string;
    }> = [];

    validPairs.forEach(pair => {
      pair.packageIds.forEach(packageId => {
        const packageOption = packageOptionsByProduct[pair.productId]?.find(
          pkg => pkg.value === packageId,
        );
        formValue.push({
          productId: pair.productId,
          productName: pair.productName,
          packageId: packageId,
          packageName: packageOption?.label || '',
        });
      });
    });

    form.setValue('productRestrictions', formValue);
  }, [productPackagePairs, packageOptionsByProduct, form]);

  const handleAddProduct = () => {
    const newPair: ProductPackagePair = {
      id: Date.now().toString(),
      productId: '',
      packageIds: [],
      productName: '',
    };
    setProductPackagePairs(prev => [...prev, newPair]);
  };

  const handleRemoveProduct = (pairId: string) => {
    if (productPackagePairs.length > 1) {
      setProductPackagePairs(prev => prev.filter(pair => pair.id !== pairId));
    }
  };

  const handleProductChange = (pairId: string, productId: string) => {
    // Find the product name from productData
    const selectedProduct = productData.find(p => p.productId === productId);

    setProductPackagePairs(prev =>
      prev.map(pair =>
        pair.id === pairId
          ? {
            ...pair,
            productId,
            productName: selectedProduct?.productName || '',
            packageIds: [], // Reset packages when product changes
          }
          : pair,
      ),
    );
  };

  const handlePackageChange = (pairId: string, packageIds: string[]) => {
    setProductPackagePairs(prev =>
      prev.map(p =>
        p.id === pairId
          ? {
            ...p,
            packageIds,
          }
          : p,
      ),
    );
  };

  const handleSubmit = async (data: CouponFormData) => {
    setLoading(true);

    // Filter out incomplete product-package pairs
    const validProductPackagePairs = productPackagePairs.filter(
      pair => pair.productId && pair.packageIds.length > 0,
    );

    // Expand pairs into individual entries for each package
    const productRestrictions: Array<{
      productId: string;
      productName: string;
      packageId: string;
      packageName: string;
    }> = [];

    validProductPackagePairs.forEach(pair => {
      pair.packageIds.forEach(packageId => {
        const packageOption = packageOptionsByProduct[pair.productId]?.find(
          pkg => pkg.value === packageId,
        );
        productRestrictions.push({
          productId: pair.productId,
          productName: pair.productName,
          packageId: packageId,
          packageName: packageOption?.label || '',
        });
      });
    });

    const formData = {
      ...data,
      isActive: data.isActive === 'true',
      validFrom: convertToUTC(data.validFrom),
      validUntil: convertToUTC(data.validUntil),
      productRestrictions,
    };

    let response;

    try {
      if (coupon) {
        response = await apiClient.put(
          API_END_POINTS.COUPON_UPDATE + coupon.id,
          { data: formData },
        );
      } else {
        response = await apiClient.post(API_END_POINTS.COUPON_CREATE, {
          data: formData,
        });
      }
      if (isSuccessResponse(response.statusCode)) {
        onSave();
        form.reset();
        onClose();
        toast.success(
          coupon ? 'Coupon updated successfully' : 'Coupon created successfully',
        );
      } else {
        toast.error(response.message || 'Failed to save coupon');
      }
    } catch (error) {
      console.error('Error saving coupon:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    form.reset();
    setProductPackagePairs([
      { id: '1', productId: '', packageIds: [], productName: '' },
    ]);
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-h-[80vh] w-2/3 overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{coupon ? 'Edit Coupon' : 'Add New Coupon'}</DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(handleSubmit)}
            className="space-y-4"
          >
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Name *</FormLabel>
                    <FormControl>
                      <Input {...field} placeholder="Enter coupon name" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="code"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Code *</FormLabel>
                    <FormControl>
                      <Input
                        {...field}
                        placeholder="Enter coupon code"
                        style={{ textTransform: 'uppercase' }}
                        onChange={e =>
                          field.onChange(e.target.value.toUpperCase())
                        }
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description *</FormLabel>
                  <FormControl>
                    <Textarea
                      {...field}
                      placeholder="Enter coupon description"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="grid grid-cols-3 gap-4">
              <FormField
                control={form.control}
                name="type"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Type *</FormLabel>
                    <Select
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select type" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="PERCENTAGE">Percentage</SelectItem>
                        <SelectItem value="FIXED">Fixed</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="value"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Value *</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="isActive"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Status *</FormLabel>
                    <Select
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select status" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="true">Active</SelectItem>
                        <SelectItem value="false">Inactive</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="validFrom"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Valid From *</FormLabel>
                    <FormControl>
                      <Input
                        type="datetime-local"
                        {...field}
                        onClick={e => {
                          const input = e.target as HTMLInputElement;
                          input.showPicker();
                        }}
                        className="w-full"
                        min={new Date().toISOString().slice(0, 16)}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="validUntil"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Valid Until *</FormLabel>
                    <FormControl>
                      <Input
                        type="datetime-local"
                        {...field}
                        onClick={e => {
                          const input = e.target as HTMLInputElement;
                          input.showPicker();
                        }}
                        className="w-full"
                        min={new Date().toISOString().slice(0, 16)}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="usageLimit"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Usage Limit *</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="minPurchaseAmount"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Min Purchase Amount *</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* Product-Package Selection */}
            <div className="col-span-full">
              <Card className="p-4">
                <div className="mb-4 flex items-center justify-between">
                  <div>
                    <CardTitle>Product & Package Restrictions</CardTitle>
                    <CardDescription>
                      Choose products and their packages for coupon restrictions
                    </CardDescription>
                  </div>
                  <button
                    type="button"
                    onClick={handleAddProduct}
                    className="flex items-center gap-2 rounded bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary/90"
                  >
                    <Plus className="size-4" /> Add Product-Package
                  </button>
                </div>

                <div className="space-y-4">
                  {productPackagePairs.map((pair, index) => (
                    <div
                      key={pair.id}
                      className="rounded border border-card-border p-4"
                    >
                      <div className="mb-3 flex items-center justify-between">
                        <p className="text-xl font-medium">
                          Product Set {index + 1}
                          {pair.productName && (
                            <span className="ml-2 text-sm text-muted-foreground">
                              ({pair.productName})
                            </span>
                          )}
                        </p>
                        {productPackagePairs.length > 1 && (
                          <button
                            type="button"
                            onClick={() => handleRemoveProduct(pair.id)}
                            className="p-1 text-red-500 hover:text-red-700"
                          >
                            <Trash2 className="size-4" />
                          </button>
                        )}
                      </div>

                      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
                        {/* Product Selection */}
                        <div className="flex flex-col space-y-2">
                          <Label htmlFor={`product-${pair.id}`}>
                            Product *
                          </Label>
                          <SearchSelect
                            items={productOptions.map(option => ({
                              value: option.value,
                              label: option.label,
                            }))}
                            value={pair.productId}
                            onValueChange={value =>
                              handleProductChange(pair.id, value)
                            }
                          />
                        </div>

                        {/* Package Selection */}
                        <div className="flex flex-col space-y-2">
                          <Label htmlFor={`package-${pair.id}`}>
                            Packages *
                          </Label>
                          <CustomSelect
                            data={
                              pair.productId
                                ? packageOptionsByProduct[pair.productId] || []
                                : []
                            }
                            key={`package-${pair.id}-${pair.productId}`}
                            isMulti
                            name={`package-${pair.id}`}
                            value={
                              pair.packageIds
                                .map(id =>
                                  packageOptionsByProduct[pair.productId]?.find(
                                    pkg => pkg.value === id,
                                  ),
                                )
                                .filter(Boolean) as TMultiValue<ISelectOption>
                            }
                            handleChange={(
                              newValue:
                                | TMultiValue<ISelectOption>
                                | TSingleValue<ISelectOption>,
                            ) => {
                              const ids = Array.isArray(newValue)
                                ? newValue.map(item => item.value)
                                : newValue
                                  ? [(newValue as ISelectOption).value]
                                  : [];
                              handlePackageChange(pair.id, ids);
                            }}
                            isDisabled={!pair.productId}
                            placeholder={
                              pair.productId
                                ? 'Select packages'
                                : 'Select a product first'
                            }
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            </div>

            <div className="flex justify-end space-x-2">
              <Button type="button" variant="outline" onClick={handleClose}>
                Cancel
              </Button>
              <Button type="submit" disabled={loading}>
                {coupon
                  ? loading
                    ? 'Updating...'
                    : 'Update'
                  : loading
                    ? 'Creating...'
                    : 'Create'}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};

export default CouponModal;
