export enum CouponType {
  FLAT = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
}

export enum CouponStatus {
  ALL = 'ALL',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  INACTIVE = 'INACTIVE',
}

export interface ICoupon {
  id: string;
  name: string;
  description: string;
  code: string;
  autoGenerated: boolean;
  type: CouponType;
  status: CouponStatus;
  value: number;
  currency: string;
  validFrom: string;
  validUntil: string;
  usageLimit: number;
  totalUsed: number;
  minPurchaseAmount: number;
  geographicRestrictions: string[];
  qrCodeUrl: string;
  urlCoupon: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  active: boolean;
  isActive: boolean;
  isStackable: boolean;
  productRestrictions?: Array<{
    productId: string;
    productName: string;
    packageId: string;
    packageName: string;
  }>;
}

export interface ICouponSummary {
  totalCoupons: number;
  activeCoupons: number;
  inactiveCoupons: number;
  totalUsage: number;
  estimatedSavings: number;
}
