package com.aspire.asat.billing.dto;

import com.aspire.asat.billing.validation.CurrencyRequiredIfFixed;
import com.aspire.asat.billing.validation.ValidCouponType;
import com.aspire.asat.billing.validation.ValidDateRange;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.time.Instant;
import java.util.List;

@Data
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
@ValidDateRange
@CurrencyRequiredIfFixed
public class   CouponCreateRequestDTO {

    @NotBlank(message = "Coupon name must not be blank")
    private String name;

    @NotBlank(message = "Description must not be blank")
    private String description;

    @NotBlank(message = "Coupon code must not be blank")
    private String code;

    private boolean autoGenerated;

    @NotBlank(message = "Coupon type must not be blank")
    @ValidCouponType
    private String type;

    @NotNull(message = "Value is required for the coupon")
    private Double value;

    private String currency; // optionally you can validate this based on type == FIXED

    @NotNull(message = "Start date (validFrom) is required")
    private Instant validFrom;

    @NotNull(message = "End date (validUntil) is required")
    private Instant validUntil;

    @NotNull(message = "Usage limit must be specified")
    private Integer usageLimit;

    private Double minPurchaseAmount;

    private boolean isActive = true;
    private boolean isStackable = false;

    private List<ProductRestrictionDTO> productRestrictions;

    @io.swagger.v3.oas.annotations.media.Schema(
            description = "List of country IDs (UUIDs) for geographic restrictions",
            example = "[\"ad30c701-9827-4fb7-b404-fac01fed5e77\", \"b1234567-89ab-cdef-0123-456789abcdef\"]"
    )
    private List<String> geographicRestrictions;
}
