package com.aspire.asat.billing.dto;

import lombok.Data;

import java.time.Instant;
import java.util.List;

@Data
public class CouponCreateResponseDTO {

    private String id;

    private String name;
    private String description;
    private String code;
    private boolean autoGenerated;

    private String type;
    private Double value;
    private String currency;

    private Instant validFrom;
    private Instant validUntil;

    private Integer usageLimit;
    private Integer totalUsed; // Newly added

    private Double minPurchaseAmount;

    private boolean isActive;
    private boolean isStackable;

    private List<ProductRestrictionDTO> productRestrictions;
    
    @io.swagger.v3.oas.annotations.media.Schema(
            description = "List of country IDs (UUIDs) for geographic restrictions",
            example = "[\"ad30c701-9827-4fb7-b404-fac01fed5e77\"]"
    )
    private List<String> geographicRestrictions;

    private String qrCodeUrl;
    private String urlCoupon;

    private String createdBy;
    private Instant createdAt;
    private Instant updatedAt;
}
