plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'application'
}

application {
    mainClass = 'com.aspire.asat.vps.VpsApplication'
}

group 'com.aspire.asat.vps'

dependencies {

    implementation project(':services:vps:api')
    implementation project(':services:vps:core')
    implementation project(':common:core')
    implementation project.rootProject.ext.libraries.development.springDocUi
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.0.6'
    implementation project.rootProject.ext.libraries.core.springBootStarter
    implementation project.rootProject.ext.libraries.core.springBootStarterWeb
    testImplementation platform(project.rootProject.ext.libraries.test.junitBom)
    testImplementation project.rootProject.ext.libraries.test.junitJupiter

}

tasks.test {
    useJUnitPlatform()
}