apiVersion: v1
kind: Service
metadata:
    name: asat-billing-service
    namespace: dev
spec:
    # This selector is crucial. It must match the 'app' label in your Deployment's pod template.
    selector:
        app: asat-billing
    ports:
        - name: http
          protocol: TCP
            # The port on the Service itself that other services in the cluster will use.
          port: 80
            # The port on the pod that the service will forward traffic to (must match containerPort).
          targetPort: 6060
    # Type: ClusterIP exposes the service on an internal-only IP within the cluster.
    # This is the default and most common type for internal microservice communication,
    # which is then exposed externally via an Ingress controller.
#    type: ClusterIP