plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'application'
}

application {
    mainClass = 'com.aspire.asat.phishing.PhishingApplication'
}

group 'com.aspire.asat.phishing'

dependencies {


    implementation project(':services:phishing:api')
    implementation project(':services:phishing:core')
    implementation project(':common:core')

    implementation project.rootProject.ext.libraries.development.springDocUi

    implementation project.rootProject.ext.libraries.core.springBootStarter
    implementation project.rootProject.ext.libraries.core.springBootStarterWeb
    implementation project.rootProject.ext.libraries.core.springBootStarterThymeLeaf
    implementation project.rootProject.ext.libraries.core.springBootStarterDataMongo
    implementation project.rootProject.ext.libraries.core.webflux

    implementation project.rootProject.ext.libraries.core.awsSdkSqs
    implementation project.rootProject.ext.libraries.core.awsSdkS3
    implementation project.rootProject.ext.libraries.core.awsSdkSes
    implementation project.rootProject.ext.libraries.core.awsSdkRekognition
    implementation project.rootProject.ext.libraries.core.springCloudAwsStarterSqs

    testImplementation platform(project.rootProject.ext.libraries.test.junitBom)
    testImplementation project.rootProject.ext.libraries.test.junitJupiter

}

tasks.test {
    useJUnitPlatform()
}

