import { safeWindowOpen } from 'home-module/security';
import { Badge } from 'common/Badge';
import { Button } from 'common/Button';
import { Card, CardContent, CardHeader, CardTitle } from 'common/Card';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from 'common/Dialog';
import { useAPI } from 'hooks/UseAPI';
import {
  AlertCircle,
  Calendar,
  CheckCircle,
  Clock,
  Download,
  FileText,
  Package,
  Receipt,
  User,
  XCircle,
} from 'lucide-react';
import { useEffect, useState } from 'react';
import { API_END_POINTS } from 'routes/APIEndpoints';

interface ProductSelection {
  productId: string;
  packageId: string;
  licenseCount: number;
  pricePerLicense: number;
  validityPeriod: number;
  validityUnit: string;
  productName: string;
  packageName: string;
}

interface Invoice {
  id: string;
  clientAdminId: string;
  clientName: string;
  clientProductIds: string[];
  subtotal: number;
  discountAmount: number;
  vatAmount: number;
  totalAmount: number;
  invoicePdfLink: string;
  status: 'PAID' | 'PENDING' | 'OVERDUE' | 'CANCELLED';
  createdAt: string;
  paidAt?: string;
  productSelections: ProductSelection[];
}

interface CouponDetails {
  id: string;
  name: string;
  description: string;
  code: string;
  autoGenerated: boolean;
  type: 'PERCENTAGE' | 'FIXED';
  value: number;
  currency: string;
  validFrom: number;
  validUntil: number;
  usageLimit: number;
  totalUsed: number;
  minPurchaseAmount: number;
  productRestrictions: string[];
  geographicRestrictions: string[];
  qrCodeUrl: string;
  urlCoupon: string;
  createdBy: string | null;
  createdAt: number;
  updatedAt: number;
  active: boolean;
  stackable: boolean;
}

interface IProps {
  paymentId: string;
  open: boolean;
  onClose: () => void;
}

const getStatusBadge = (status: string) => {
  const statusConfig = {
    PAID: { color: 'bg-green-100 text-green-800', icon: CheckCircle },
    PENDING: { color: 'bg-yellow-100 text-yellow-800', icon: Clock },
    OVERDUE: { color: 'bg-red-100 text-red-800', icon: AlertCircle },
    CANCELLED: { color: 'bg-gray-100 text-gray-800', icon: XCircle },
  };

  const config =
    statusConfig[status as keyof typeof statusConfig] || statusConfig.PENDING;
  const IconComponent = config.icon;

  return (
    <Badge className={`${config.color} flex items-center gap-1`}>
      <IconComponent className="size-3" />
      {status}
    </Badge>
  );
};

const AspireAdminClientPendingDetails = ({
  paymentId,
  open,
  onClose,
}: IProps) => {
  const [couponCode, setCouponCode] = useState('');
  const [couponDetails, setCouponDetails] = useState<CouponDetails | null>(
    null,
  );
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string>('');
  const [paymentDetails, setPaymentDetails] = useState<any>(null);
  const [detailsLoading, setDetailsLoading] = useState(false);
  const [paymentLoading, setPaymentLoading] = useState<boolean>(false);
  const [paymentMethod, setPaymentMethod] = useState('');

  const apiClient = useAPI();

  useEffect(() => {
    if (paymentId) {
      fetchPaymentDetails();
    }
  }, [paymentId]);

  const fetchPaymentDetails = async () => {
    setDetailsLoading(true);

    try {
      const response = await apiClient.get(
        API_END_POINTS.INVOICE_DETAILS + paymentId,
      );
      setPaymentDetails(response.data);
      setCouponDetails(null);
      setCouponCode('');
    } catch (error) {
      console.error('Error fetching payment details:', error);
      setError('Failed to fetch payment details.');
    } finally {
      setDetailsLoading(false);
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    if (!dateString) return '';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="size-5" />
              Invoice Details
            </DialogTitle>
            <DialogDescription>
              Complete details for invoice {paymentDetails?.id}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6">
            {/* Basic Invoice Information */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Receipt className="size-4" />
                  Invoice Information
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4 text-sm md:grid-cols-3">
                  <div>
                    <span className="font-medium text-muted-foreground">
                      Invoice ID:
                    </span>
                    <p className="font-mono text-sm">{paymentDetails?.id}</p>
                  </div>
                  <div>
                    <span className="flex items-center gap-1 font-medium text-muted-foreground">
                      <User className="size-3" />
                      Client:
                    </span>
                    <p>{paymentDetails?.clientName}</p>
                  </div>
                  <div>
                    <span className="font-medium text-muted-foreground">
                      Status:
                    </span>
                    <div className="mt-1">
                      {getStatusBadge(paymentDetails?.status)}
                    </div>
                  </div>
                  <div>
                    <span className="flex items-center gap-1 font-medium text-muted-foreground">
                      <Calendar className="size-3" />
                      Created:
                    </span>
                    <p>{formatDate(paymentDetails?.createdAt)}</p>
                  </div>
                  {paymentDetails?.paidAt && (
                    <div>
                      <span className="flex items-center gap-1 font-medium text-muted-foreground">
                        <CheckCircle className="size-3" />
                        Paid:
                      </span>
                      <p>{formatDate(paymentDetails?.paidAt)}</p>
                    </div>
                  )}
                  <div>
                    <span className="flex items-center gap-1 font-medium text-muted-foreground">
                      <Download className="size-3" />
                      PDF:
                    </span>
                    <Button
                      variant="link"
                      size="sm"
                      className="h-auto p-0 text-blue-600"
                      onClick={() =>
                        safeWindowOpen(paymentDetails?.invoicePdfLink, '_blank')
                      }
                    >
                      Download
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Product Selections */}
            {paymentDetails?.productSelections &&
              paymentDetails?.productSelections?.length > 0 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-lg">
                      <Package className="size-4" />
                      Product Details
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      {paymentDetails.productSelections.map(
                        (product: any, index: number) => (
                          <div key={index} className="rounded-lg border p-3">
                            <div className="grid grid-cols-2 gap-3 text-sm md:grid-cols-4">
                              <div>
                                <span className="font-medium text-muted-foreground">
                                  Product:
                                </span>
                                <p>{product.productName}</p>
                              </div>
                              <div>
                                <span className="font-medium text-muted-foreground">
                                  Package:
                                </span>
                                <p>{product.packageName}</p>
                              </div>
                              <div>
                                <span className="font-medium text-muted-foreground">
                                  Licenses:
                                </span>
                                <p>{product.licenseCount}</p>
                              </div>
                              <div>
                                <span className="font-medium text-muted-foreground">
                                  Price/License:
                                </span>
                                <p>{formatCurrency(product.pricePerLicense)}</p>
                              </div>
                              <div className="col-span-2 md:col-span-4">
                                <span className="font-medium text-muted-foreground">
                                  Validity:
                                </span>
                                <p>
                                  {product.validityPeriod}{' '}
                                  {product.validityUnit.toLowerCase()}(s)
                                </p>
                              </div>
                            </div>
                          </div>
                        ),
                      )}
                    </div>
                  </CardContent>
                </Card>
              )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default AspireAdminClientPendingDetails;
