import { safeRedirect } from 'home-module/security';
import { Badge } from 'common/Badge';
import { Button } from 'common/Button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from 'common/Card';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from 'common/Dialog';
import { Separator } from 'common/Separator';
import { useAPI } from 'hooks/UseAPI';
import { useAuth } from 'hooks/UseAuth';
import {
  AlertCircle,
  Calendar,
  CheckCircle,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Loader2,
  MessageCircle,
  Package,
  Percent,
  Receipt,
  Send,
  Tag,
  XCircle,
} from 'lucide-react';
import { Fragment, useEffect, useState } from 'react';
import { API_END_POINTS } from 'routes/APIEndpoints';
import { ROLE } from 'utils/Role';
import ClientPaymentModal from './ClientPaymentModal';
import MSPPaymentModal, { PaymentData } from './MSPPaymentModal';
import {
  IInvoiceDetails,
  IPaymentComment,
  PaymentMethod,
} from 'models/Payment';
import { formatDateTime, humanizeText, isSuccessResponse } from 'utils/Helper';
import { toast } from 'react-toastify';
import { useNavigate } from 'react-router-dom';
import { routes } from 'routes/Routes';
import { IDropdownOption, Status } from 'models/Global';
import { useStore } from 'hooks/UseStore';
import ActionStatusIcon from 'components/ActionStatusIcon';
import { Input } from 'common/Input';
import { Label } from 'common/Label';
import { Textarea } from 'common/Textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from 'common/Select';

interface CouponDetails {
  id: string;
  name: string;
  description: string;
  code: string;
  autoGenerated: boolean;
  type: 'PERCENTAGE' | 'FIXED';
  value: number;
  currency: string;
  validFrom: number;
  validUntil: number;
  usageLimit: number;
  totalUsed: number;
  minPurchaseAmount: number;
  productRestrictions: Array<{
    productId: string;
    packageId: string;
  }>;
  geographicRestrictions: string[];
  qrCodeUrl: string;
  urlCoupon: string;
  createdBy: string | null;
  createdAt: number;
  updatedAt: number;
  active: boolean;
  stackable: boolean;
  paymentDetails: {
    bankName: string;
    accountNumber: string;
    bankBranchName: string;
    transactionNumber: string;
    paymentDate: string;
    paymentAmount: number;
    transactionReceiptUrl: string;
  };
  paymentMethod: 'BANK_TRANSFER' | 'CHECK_PAYMENT';
}

type DiscountType = 'PERCENTAGE' | 'FLAT';

const DISCOUNT_REASON_MIN_LENGTH = 10;
const DISCOUNT_REASON_MAX_LENGTH = 500;
const MIN_PAYABLE_AFTER_DISCOUNT = 1;

const isDiscountReasonValid = (reason: string) => {
  const trimmed = reason.trim();
  return (
    trimmed.length >= DISCOUNT_REASON_MIN_LENGTH &&
    trimmed.length <= DISCOUNT_REASON_MAX_LENGTH
  );
};

const getMaxDiscountAmount = (totalAmount: number) =>
  Math.max(
    0,
    Number((totalAmount - MIN_PAYABLE_AFTER_DISCOUNT).toFixed(2)),
  );

const getDiscountAmountInDollars = (
  type: DiscountType,
  value: number,
  totalAmount: number,
) => (type === 'PERCENTAGE' ? (value / 100) * totalAmount : value);

interface IProps {
  paymentId: string;
  open: boolean;
  onClose: () => void;
}

const getStatusBadge = (status: string) => {
  const statusConfig = {
    PAID: { color: 'bg-green-100 text-green-800', icon: CheckCircle },
    PENDING: { color: 'bg-yellow-100 text-yellow-800', icon: Clock },
    OVERDUE: { color: 'bg-red-100 text-red-800', icon: AlertCircle },
    EXPIRED: { color: 'bg-red-100 text-red-800', icon: AlertCircle },
    CANCELLED: { color: 'bg-gray-100 text-gray-800', icon: XCircle },
  };

  const config =
    statusConfig[status as keyof typeof statusConfig] || statusConfig.PENDING;
  const IconComponent = config.icon;

  return (
    <Badge className={`${config.color} flex items-center gap-1`}>
      <IconComponent className="size-3" />
      {humanizeText(status)}
    </Badge>
  );
};

const InvoiceDetailsDialog = ({ paymentId, open, onClose }: IProps) => {
  const { role } = useAuth();
  const { userInfo } = useStore();
  const apiClient = useAPI();
  const navigate = useNavigate();

  const isMSP = role === ROLE.MSP_ADMIN;
  const isClientAdmin = role === ROLE.CLIENT_ADMIN;
  const isAspireAdmin = role === ROLE.ASPIRE_ADMIN;
  const [couponCode, setCouponCode] = useState('');
  const [applyCouponCode, setApplyCouponCode] = useState('');
  const [isApplyingCoupon, setIsApplyingCoupon] = useState(false);
  const [discountType, setDiscountType] = useState<DiscountType>('PERCENTAGE');
  const [discountValue, setDiscountValue] = useState<number>(0);
  const [discountReason, setDiscountReason] = useState('');
  const [isApplyingDiscount, setIsApplyingDiscount] = useState(false);
  const [couponDetails, setCouponDetails] = useState<CouponDetails | null>(
    null,
  );
  const [isFetchingCoupon, setIsFetchingCoupon] = useState(false);
  const [couponFetched, setCouponFetched] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>('');
  const [paymentDetails, setPaymentDetails] = useState<IInvoiceDetails | null>(
    null,
  );
  const [paymentLoading, setPaymentLoading] = useState<boolean>(false);
  const [showPaymentForm, setShowPaymentForm] = useState(false);
  const [comment, setComment] = useState<string>('');
  const [actionTaken, setActionTaken] = useState<string>('');
  const [nextStep, setNextStep] = useState<string>('');
  const [loadingComments, setLoadingComments] = useState<boolean>(false);
  const [comments, setComments] = useState<Array<IPaymentComment>>([]);
  const [actionTakenOptions, setActionTakenOptions] = useState<
    Array<IDropdownOption>
  >([]);
  const [nextStepOptions, setNextStepOptions] = useState<
    Array<IDropdownOption>
  >([]);
  const [commentSubmitting, setCommentSubmitting] = useState<boolean>(false);

  const hasCouponApplied = !!paymentDetails?.couponCode?.trim();
  const hasDiscountApplied = (paymentDetails?.discountAmount ?? 0) > 0;
  const isExpired = paymentDetails?.status === Status.EXPIRED;
  const canApplyCoupon =
    (isClientAdmin || isAspireAdmin) && !hasCouponApplied && !isExpired;
  const canApplyDiscount = isAspireAdmin && !hasDiscountApplied && !isExpired;
  const invoiceTotalAmount = paymentDetails?.totalAmount ?? 0;
  const maxDiscountAmount = getMaxDiscountAmount(invoiceTotalAmount);
  const maxDiscountPercentage =
    invoiceTotalAmount > 0
      ? Number(((maxDiscountAmount / invoiceTotalAmount) * 100).toFixed(2))
      : 0;
  const appliedDiscountInDollars = getDiscountAmountInDollars(
    discountType,
    discountValue,
    invoiceTotalAmount,
  );
  const isDiscountExceedingMax =
    discountValue > 0 &&
    Number(appliedDiscountInDollars.toFixed(2)) > maxDiscountAmount;

  useEffect(() => {
    if (paymentId) {
      fetchPaymentDetails();
    }
  }, [paymentId]);

  useEffect(() => {
    if (paymentDetails?.paymentDetails) {
      getComments();
      getActionTakenOptions();
      getNextStepOptions();
    }
  }, [paymentDetails]);

  const getComments = async () => {
    setLoadingComments(true);
    try {
      const response = await apiClient.get(
        API_END_POINTS.GET_COMMENTS.replace(':invoiceId', paymentId),
      );
      if (isSuccessResponse(response.statusCode)) {
        setComments(response.data);
      }
    } catch (error) {
      console.error('Error fetching comments:', error);
    } finally {
      setLoadingComments(false);
    }
  };

  const getActionTakenOptions = async () => {
    try {
      const response = await apiClient.get(
        API_END_POINTS.GET_ACTION_TAKEN_OPTIONS,
      );
      if (isSuccessResponse(response.statusCode)) {
        setActionTakenOptions(
          response.data.map((item: { id: string; name: string }) => ({
            value: item.id,
            label: item.name,
          })),
        );
      }
    } catch (error) {
      console.error('Error fetching action taken options:', error);
    }
  };

  const getNextStepOptions = async () => {
    try {
      const response = await apiClient.get(
        API_END_POINTS.GET_NEXT_STEP_OPTIONS,
      );
      if (isSuccessResponse(response.statusCode)) {
        setNextStepOptions(
          response.data.map((item: { id: string; name: string }) => ({
            value: item.id,
            label: item.name,
          })),
        );
      }
    } catch (error) {
      console.error('Error fetching next step options:', error);
    }
  };

  const handleSubmit = async () => {
    if (!comment || !actionTaken || !nextStep) {
      toast.error('Please fill in all required fields');
      return;
    }
    const payload = {
      invoiceId: paymentId,
      comment: comment.trim(),
      actionTakenId: actionTaken,
      nextStepId: nextStep,
      userName: userInfo?.email ?? '',
      userRole: role ?? '',
    };

    try {
      setCommentSubmitting(true);
      const response = await apiClient.post(API_END_POINTS.CREATE_COMMENT, {
        data: payload,
      });
      if (isSuccessResponse(response.statusCode)) {
        toast.success('Comment submitted successfully');
        getComments();
        setComment('');
        setActionTaken('');
        setNextStep('');
      } else {
        toast.error(response.data?.data?.error || 'Failed to submit comment');
      }
    } catch (error) {
      console.error('Error submitting comment:', error);
    } finally {
      setCommentSubmitting(false);
    }
  };

  const fetchPaymentDetails = async () => {
    try {
      setLoading(true);
      const response = await apiClient.get(
        API_END_POINTS.INVOICE_DETAILS + paymentId,
      );
      setPaymentDetails(response.data);
      setCouponDetails(null);
      setCouponCode('');
      setApplyCouponCode('');
      setCouponFetched(false);
      setDiscountValue(0);
      setDiscountReason('');
      setError('');
    } catch (error) {
      console.error('Error fetching payment details:', error);
    } finally {
      setLoading(false);
    }
  };

  // Automatically fetch coupon if couponCode exists in paymentDetails
  useEffect(() => {
    if (paymentDetails?.couponId) {
      fetchCouponByCode(paymentDetails.couponId);
    }
  }, [paymentDetails?.couponId]);

  const fetchCouponByCode = async (id: string) => {
    if (!id.trim()) return;

    setIsFetchingCoupon(true);
    setError('');
    setCouponFetched(false);

    try {
      const response = await apiClient.get(
        API_END_POINTS.GET_COUPON_BY_ID.replace(':id', id),
      );

      if (isSuccessResponse(response.statusCode)) {
        const fetchedCoupon = response.data;

        // Check if coupon applies to selected products
        const hasProductRestrictions =
          fetchedCoupon.productRestrictions &&
          fetchedCoupon.productRestrictions.length > 0;

        if (hasProductRestrictions) {
          // Has restrictions - check if any product matches
          const hasMatchingProduct = paymentDetails?.productSelections?.some(
            (selectedProduct: any) =>
              fetchedCoupon.productRestrictions?.some(
                (restriction: { productId: string; packageId: string }) =>
                  restriction.productId === selectedProduct.productId &&
                  restriction.packageId === selectedProduct.packageId,
              ),
          );

          if (!hasMatchingProduct) {
            // Coupon exists but not applicable to current products
            setCouponDetails(fetchedCoupon);
            setError(
              'This coupon is not applicable to your selected products/packages',
            );
            setCouponFetched(true);
            return;
          }
        }
        // No restrictions = applies to all products, or has matching products

        // Coupon is valid and applicable
        setCouponDetails(fetchedCoupon);
        setCouponCode(fetchedCoupon.code);
        setError('');
        setCouponFetched(true);
      } else {
        setError(response.message || 'Invalid coupon code');
        setCouponDetails(null);
        setCouponFetched(true);
      }
    } catch (error) {
      console.error('Error fetching coupon by code:', error);
      setError('Failed to apply coupon. Please check the code and try again.');
      setCouponDetails(null);
      setCouponFetched(true);
    } finally {
      setIsFetchingCoupon(false);
    }
  };

  const handleApplyCoupon = async () => {
    if (!applyCouponCode.trim()) {
      toast.error('Please enter a coupon code');
      return;
    }

    setIsApplyingCoupon(true);
    try {
      const response = await apiClient.post(
        API_END_POINTS.APPLY_COUPON.replace(':invoiceId', paymentId),
        {
          data: {
            couponCode: applyCouponCode.trim(),
            sendEmail: true,
          },
        },
      );

      if (isSuccessResponse(response.statusCode)) {
        toast.success(response.message || 'Coupon applied successfully');
        await fetchPaymentDetails();
      } else {
        toast.error(response.message || 'Failed to apply coupon');
      }
    } catch (error) {
      console.error('Error applying coupon:', error);
      toast.error('Failed to apply coupon. Please try again.');
    } finally {
      setIsApplyingCoupon(false);
    }
  };

  const handleApplyDiscount = async () => {
    const trimmedReason = discountReason.trim();

    if (trimmedReason.length < DISCOUNT_REASON_MIN_LENGTH) {
      toast.error(
        `Reason must be at least ${DISCOUNT_REASON_MIN_LENGTH} characters`,
      );
      return;
    }

    if (trimmedReason.length > DISCOUNT_REASON_MAX_LENGTH) {
      toast.error(
        `Reason must not exceed ${DISCOUNT_REASON_MAX_LENGTH} characters`,
      );
      return;
    }

    if (!discountValue || discountValue <= 0) {
      toast.error('Please enter a valid discount value');
      return;
    }

    if (discountType === 'PERCENTAGE' && discountValue > 100) {
      toast.error('Discount percentage cannot exceed 100%');
      return;
    }

    if (maxDiscountAmount <= 0) {
      toast.error(
        'Discount cannot be applied. At least $1 must remain payable.',
      );
      return;
    }

    if (isDiscountExceedingMax) {
      toast.error(
        `Discount cannot exceed $${maxDiscountAmount.toFixed(2)}. At least $1 must remain payable.`,
      );
      return;
    }

    const payload =
      discountType === 'PERCENTAGE'
        ? {
            discountType: 'PERCENTAGE',
            discountPercentage: discountValue,
            sendEmail: true,
            reason: trimmedReason,
          }
        : {
            discountType: 'FLAT',
            discountAmount: discountValue,
            sendEmail: true,
            reason: trimmedReason,
          };

    setIsApplyingDiscount(true);
    try {
      const response = await apiClient.post(
        API_END_POINTS.APPLY_DISCOUNT.replace(':invoiceId', paymentId),
        { data: payload },
      );

      if (isSuccessResponse(response.statusCode)) {
        toast.success(response.message || 'Discount applied successfully');
        await fetchPaymentDetails();
      } else {
        toast.error(response.message || 'Failed to apply discount');
      }
    } catch (error) {
      console.error('Error applying discount:', error);
      toast.error('Failed to apply discount. Please try again.');
    } finally {
      setIsApplyingDiscount(false);
    }
  };

  const handlePayment = async (data: PaymentData | string) => {
    setPaymentLoading(true);

    const manualPayment =
      (data as string) === PaymentMethod.BANK_TRANSFER ||
      (data as string) === PaymentMethod.CHECK_PAYMENT;

    const metadata =
      (data as string) === PaymentMethod.BANK_TRANSFER
        ? {
            bankName: paymentDetails?.paymentDetails?.bankName,
            accountNumber: paymentDetails?.paymentDetails?.accountNumber,
            bankBranchName: paymentDetails?.paymentDetails?.bankBranchName,
            transactionNumber:
              paymentDetails?.paymentDetails?.transactionNumber,
            paymentDate: paymentDetails?.paymentDetails?.paymentDate,
            paymentAmount: paymentDetails?.paymentDetails?.paymentAmount,
            transactionReceiptUrl:
              paymentDetails?.paymentDetails?.transactionReceiptUrl,
          }
        : (data as string) === PaymentMethod.CHECK_PAYMENT
          ? {
              checkNumber: paymentDetails?.paymentDetails?.checkNumber,
              bankName: paymentDetails?.paymentDetails?.bankName,
              branchName: paymentDetails?.paymentDetails?.branchName,
              paymentDate: paymentDetails?.paymentDetails?.paymentDate,
              paymentAmount: paymentDetails?.paymentDetails?.paymentAmount,
              checkImageUrl: paymentDetails?.paymentDetails?.checkImageUrl,
            }
          : null;

    const manualPaymentPayload = {
      clientId: paymentDetails?.clientAdminId,
      invoiceId: paymentDetails?.id,
      amount: paymentDetails?.totalAmount,
      currency: 'USD',
      packageItems: paymentDetails?.productSelections,
      clientRegion: 'US',
      date: new Date().toISOString(),
      paymentSources: [
        {
          method: data as string,
          amount: paymentDetails?.totalAmount,
          online: false,
          transactionId:
            paymentDetails?.paymentDetails?.transactionNumber || '',
          metadata: metadata,
        },
      ],
      couponCode: couponCode,
      subtotal: paymentDetails?.subtotal,
      vatAmount: paymentDetails?.vatAmount,
      discountPercentage: paymentDetails?.discountPercentage,
    };

    const onlinePaymentPayload = {
      clientId: paymentDetails?.clientAdminId,
      invoiceId: paymentDetails?.id,
      amount: paymentDetails?.totalAmount,
      currency: 'USD',
      packageItems: paymentDetails?.productSelections,
      clientRegion: 'US',
      date: new Date().toISOString(),
      notes: manualPayment ? 'Manual payment' : 'Online payment',
      paymentSources: [
        {
          method: data as string,
          amount: paymentDetails?.totalAmount,
          online: true,
          transactionId:
            paymentDetails?.paymentDetails?.transactionNumber || '',
        },
      ],
      couponCode: couponCode,
      subtotal: paymentDetails?.subtotal,
      vatAmount: paymentDetails?.vatAmount,
      discountPercentage: paymentDetails?.discountPercentage,
    };

    const payload = manualPayment ? manualPaymentPayload : onlinePaymentPayload;

    try {
      const response = await apiClient.post(
        manualPayment
          ? API_END_POINTS.MANUAL_PAYMENT
          : API_END_POINTS.ONLINE_PAYMENT,
        {
          data: payload,
        },
      );
      if (isSuccessResponse(response.statusCode)) {
        if (manualPayment) {
          toast.success('Payment processed successfully');
          navigate(routes.paymentHistory.path);
        } else {
          safeRedirect(response.data.checkoutUrl);
        }
      }
    } catch (error) {
      console.error('Error processing payment:', error);
    } finally {
      setPaymentLoading(false);
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 10,
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    if (!dateString) return '';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const handleDownloadReceipt = async (id: string) => {
    try {
      const response = await apiClient.get(
        API_END_POINTS.DOWNLOAD_INVOICE_PDF.replace(':id', id),
        {
          responseType: 'blob',
        },
      );

      const blob = new Blob([response], {
        type: 'application/pdf',
      });

      const url = window.URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = url;
      link.download = `invoice-${id}.pdf`;
      document.body.appendChild(link);
      link.click();

      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading receipt:', error);
    }
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-h-[90vh] w-2/3 overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="size-5" />
              Invoice Details
            </DialogTitle>
            <DialogDescription>
              Complete details for invoice {paymentDetails?.id}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6">
            {/* Basic Invoice Information */}
            {loading ? (
              <div className="py-4 text-center text-muted-foreground">
                Loading...
              </div>
            ) : (
              <Fragment>
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-lg">
                      <Receipt className="size-4" />
                      Invoice Information
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 gap-4 text-sm md:grid-cols-3">
                      <div>
                        <span className="font-medium text-muted-foreground">
                          Invoice ID:
                        </span>
                        <p className="font-mono text-sm">
                          {paymentDetails?.id}
                        </p>
                      </div>
                      <div>
                        <span className="font-medium text-muted-foreground">
                          Status:
                        </span>
                        <div className="mt-1 w-fit">
                          {getStatusBadge(paymentDetails?.status || '')}
                        </div>
                      </div>
                      {paymentDetails?.status === Status.EXPIRED && (
                        <div className="col-span-2 md:col-span-3">
                          <span className="font-medium text-muted-foreground">
                            Reason:
                          </span>
                          <p className="mt-1 whitespace-pre-wrap">
                            {paymentDetails?.reason ||
                              paymentDetails?.statusNote ||
                              'N/A'}
                          </p>
                        </div>
                      )}
                      {paymentDetails?.couponCode && (
                        <div>
                          <span className="font-medium text-muted-foreground">
                            Applied Coupon Code:
                          </span>
                          <div className="mt-1 space-y-1">
                            <Badge variant="default">
                              {paymentDetails?.couponCode}
                            </Badge>
                            {isFetchingCoupon && (
                              <p className="text-xs text-blue-500">
                                <Loader2 className="mr-1 inline size-3 animate-spin" />
                                Loading coupon details...
                              </p>
                            )}
                            {!isFetchingCoupon &&
                              couponFetched &&
                              couponDetails &&
                              !error && (
                                <p className="text-xs text-green-600">
                                  ✓ Coupon loaded -{' '}
                                  {couponDetails.type === 'PERCENTAGE'
                                    ? `${couponDetails.value}% off`
                                    : `${formatCurrency(couponDetails.value)} off`}
                                </p>
                              )}
                            {!isFetchingCoupon && couponFetched && error && (
                              <p className="text-xs text-red-500">{error}</p>
                            )}
                            {!isFetchingCoupon &&
                              couponFetched &&
                              !couponDetails &&
                              !error && (
                                <p className="text-xs text-yellow-600">
                                  Coupon not found or inactive
                                </p>
                              )}
                          </div>
                        </div>
                      )}
                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          <Calendar className="size-3" />
                          Created Date:
                        </span>
                        <p>{formatDate(paymentDetails?.createdAt || '')}</p>
                      </div>
                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          Sub Total Amount:
                        </span>
                        <p>{formatCurrency(paymentDetails?.subtotal ?? 0)}</p>
                      </div>
                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          Coupon Discount Amount:
                        </span>
                        <p>
                          {formatCurrency(
                            paymentDetails?.couponDiscountAmount ?? 0,
                          )}
                        </p>
                      </div>
                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          Vat Percentage:
                        </span>
                        <p>{paymentDetails?.vatPercentage}%</p>
                      </div>
                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          Vat Amount:
                        </span>
                        <p>{formatCurrency(paymentDetails?.vatAmount ?? 0)}</p>
                      </div>
                      {paymentDetails?.discountType === 'PERCENTAGE' && (
                        <div>
                          <span className="flex items-center gap-1 font-medium text-muted-foreground">
                            Discount Percentage:
                          </span>
                          <p>{paymentDetails?.discountPercentage ?? 0}%</p>
                        </div>
                      )}
                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          Discount Amount:
                        </span>
                        <p>
                          {formatCurrency(paymentDetails?.discountAmount ?? 0)}
                        </p>
                      </div>

                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          Total Amount:
                        </span>
                        <p>
                          {formatCurrency(paymentDetails?.totalAmount ?? 0)}
                        </p>
                      </div>

                      <div>
                        <span className="flex items-center gap-1 font-medium text-muted-foreground">
                          <Download className="size-3" />
                          Invoice:
                        </span>
                        <Button
                          variant="link"
                          size="sm"
                          className="h-auto p-0 text-blue-600"
                          onClick={() =>
                            handleDownloadReceipt(paymentDetails?.id ?? '')
                          }
                        >
                          Download
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Product Selections */}
                {paymentDetails?.productSelections &&
                  paymentDetails?.productSelections?.length > 0 && (
                    <Card>
                      <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-lg">
                          <Package className="size-4" />
                          Product Details
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="space-y-3">
                          {paymentDetails.productSelections.map(
                            (product: any, index: number) => {
                              // Check if this product/package is eligible for coupon
                              const isCouponEligible =
                                couponDetails &&
                                (!couponDetails.productRestrictions ||
                                  couponDetails.productRestrictions.length ===
                                    0 ||
                                  couponDetails.productRestrictions?.some(
                                    (restriction: {
                                      productId: string;
                                      packageId: string;
                                    }) =>
                                      restriction.productId ===
                                        product.productId &&
                                      restriction.packageId ===
                                        product.packageId,
                                  ));

                              return (
                                <div
                                  key={index}
                                  className="rounded-lg border border-card-border p-3"
                                >
                                  <div className="grid grid-cols-2 gap-3 text-sm md:grid-cols-4">
                                    <div>
                                      <span className="font-medium text-muted-foreground">
                                        Product:
                                      </span>
                                      <p>{product.productName}</p>
                                    </div>
                                    <div>
                                      <span className="font-medium text-muted-foreground">
                                        Package:
                                      </span>
                                      <p>{product.packageName}</p>
                                    </div>
                                    <div>
                                      <span className="font-medium text-muted-foreground">
                                        Licenses:
                                      </span>
                                      <p>{product.licenseCount}</p>
                                    </div>
                                    <div>
                                      <span className="font-medium text-muted-foreground">
                                        Price/License:
                                      </span>
                                      <p>
                                        {formatCurrency(
                                          product.pricePerLicense,
                                        )}
                                      </p>
                                    </div>
                                    <div className="col-span-1">
                                      <span className="font-medium text-muted-foreground">
                                        Validity:
                                      </span>
                                      <p>
                                        {product.validityPeriod}{' '}
                                        {product.validityUnit.toLowerCase()}(s)
                                      </p>
                                      {isCouponEligible &&
                                        paymentDetails?.couponDiscountAmount &&
                                        paymentDetails?.couponDiscountAmount >
                                          0 && (
                                          <p className="mt-3 text-xs text-primary bg-primary/10 rounded-md p-1 text-center">
                                            ✓ Coupon applicable
                                          </p>
                                        )}
                                    </div>
                                    <div className="col-span-1">
                                      <span className="font-medium text-muted-foreground">
                                        Total Amount:
                                      </span>
                                      <p>
                                        {formatCurrency(
                                          product.pricePerLicense *
                                            product.licenseCount *
                                            product.validityPeriod,
                                        )}
                                      </p>
                                    </div>
                                  </div>
                                </div>
                              );
                            },
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  )}

                {/* Apply Coupon */}
                {canApplyCoupon && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2 text-lg">
                        <Tag className="size-4" />
                        Apply Coupon
                      </CardTitle>
                      <CardDescription>
                        Enter a coupon code to apply a discount to this invoice.
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-3">
                        <div className="flex gap-2">
                          <div className="flex-1">
                            <Input
                              placeholder="Enter coupon code"
                              value={applyCouponCode}
                              onChange={e => setApplyCouponCode(e.target.value)}
                              disabled={isApplyingCoupon}
                            />
                          </div>
                          <Button
                            onClick={handleApplyCoupon}
                            disabled={
                              isApplyingCoupon || !applyCouponCode.trim()
                            }
                            variant="outline"
                          >
                            {isApplyingCoupon ? (
                              <Loader2 className="size-4 animate-spin" />
                            ) : (
                              'Apply'
                            )}
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Apply Discount */}
                {canApplyDiscount && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2 text-lg">
                        <Percent className="size-4" />
                        Apply Discount
                      </CardTitle>
                      <CardDescription>
                        Apply a percentage or flat discount to this invoice.
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-4">
                        <div className="flex gap-2">
                          <div className="flex-1">
                            <Label>Discount Type</Label>
                            <Select
                              value={discountType}
                              onValueChange={value =>
                                setDiscountType(value as DiscountType)
                              }
                            >
                              <SelectTrigger>
                                <SelectValue placeholder="Select discount type" />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="PERCENTAGE">
                                  Percentage
                                </SelectItem>
                                <SelectItem value="FLAT">
                                  Flat Amount
                                </SelectItem>
                              </SelectContent>
                            </Select>
                          </div>

                          <div className="flex-1">
                            <Label htmlFor="discountValue">
                              Discount{' '}
                              {discountType === 'PERCENTAGE' ? '(%)' : '($)'}
                            </Label>
                            <Input
                              id="discountValue"
                              type="number"
                              value={discountValue || ''}
                              onChange={e =>
                                setDiscountValue(
                                  parseFloat(e.target.value) || 0,
                                )
                              }
                              placeholder="0"
                              min="0"
                              max={
                                discountType === 'PERCENTAGE'
                                  ? maxDiscountPercentage
                                  : maxDiscountAmount || undefined
                              }
                              step="0.01"
                              disabled={isApplyingDiscount}
                            />
                            <p className="mt-1 text-xs text-muted-foreground">
                              Maximum{' '}
                              {discountType === 'PERCENTAGE'
                                ? `${maxDiscountPercentage}%`
                                : `$${maxDiscountAmount.toFixed(2)}`}{' '}
                              (at least $1 must remain payable)
                            </p>
                          </div>
                        </div>

                        <div className="space-y-2">
                          <Label htmlFor="discountReason">
                            Reason <span className="text-destructive">*</span>
                          </Label>
                          <Textarea
                            id="discountReason"
                            value={discountReason}
                            onChange={e =>
                              setDiscountReason(
                                e.target.value.slice(
                                  0,
                                  DISCOUNT_REASON_MAX_LENGTH,
                                ),
                              )
                            }
                            placeholder="e.g. Finance approval"
                            rows={2}
                            maxLength={DISCOUNT_REASON_MAX_LENGTH}
                            disabled={isApplyingDiscount}
                          />
                          <p className="text-xs text-muted-foreground">
                            {discountReason.trim().length}/
                            {DISCOUNT_REASON_MAX_LENGTH} characters (minimum{' '}
                            {DISCOUNT_REASON_MIN_LENGTH})
                          </p>
                        </div>

                        <div className="flex justify-end">
                          <Button
                            onClick={handleApplyDiscount}
                            disabled={
                              isApplyingDiscount ||
                              !isDiscountReasonValid(discountReason) ||
                              !discountValue ||
                              maxDiscountAmount <= 0 ||
                              isDiscountExceedingMax
                            }
                          >
                            {isApplyingDiscount ? (
                              <>
                                <Loader2 className="mr-2 size-4 animate-spin" />
                                Applying...
                              </>
                            ) : (
                              'Apply Discount'
                            )}
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Amount Breakdown */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-lg">
                      <DollarSign className="size-4" />
                      Payable Amount
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      <div className="flex justify-between text-sm">
                        <span>Subtotal:</span>
                        <span>
                          {formatCurrency(paymentDetails?.subtotal ?? 0)}
                        </span>
                      </div>

                      {paymentDetails?.couponDiscountAmount &&
                      paymentDetails?.couponDiscountAmount > 0 ? (
                        <>
                          <div className="flex justify-between text-sm text-green-600">
                            <span>
                              Coupon Discount ({paymentDetails?.couponCode}):
                            </span>
                            <span>
                              -
                              {formatCurrency(
                                paymentDetails?.couponDiscountAmount,
                              )}
                            </span>
                          </div>
                          <div className="flex justify-between text-sm font-medium">
                            <span>After Coupon:</span>
                            <span>
                              {formatCurrency(
                                paymentDetails?.subtotal -
                                  paymentDetails?.couponDiscountAmount,
                              )}
                            </span>
                          </div>
                        </>
                      ) : null}

                      {paymentDetails?.discountAmount &&
                      paymentDetails?.discountAmount > 0 ? (
                        <>
                          <div className="flex justify-between text-sm text-green-600">
                            <span>
                              Discount{' '}
                              {paymentDetails?.discountType === 'PERCENTAGE'
                                ? `(${paymentDetails?.discountPercentage}%)`
                                : '(Flat)'}
                              :
                            </span>
                            <span>
                              -{formatCurrency(paymentDetails?.discountAmount)}
                            </span>
                          </div>
                          <div className="flex justify-between text-sm font-medium">
                            <span>After Discount:</span>
                            <span>
                              {formatCurrency(
                                paymentDetails?.subtotal -
                                  paymentDetails?.couponDiscountAmount -
                                  paymentDetails?.discountAmount,
                              )}
                            </span>
                          </div>
                        </>
                      ) : null}

                      {(paymentDetails?.couponDiscountAmount &&
                        paymentDetails?.couponDiscountAmount > 0) ||
                      (paymentDetails?.discountAmount &&
                        paymentDetails?.discountAmount > 0) ? (
                        <Separator />
                      ) : null}

                      {(paymentDetails?.vatPercentage ?? 0) > 0 && (
                        <div className="flex justify-between text-sm text-yellow-600">
                          <span>VAT ({paymentDetails?.vatPercentage}%):</span>
                          <span>
                            +{formatCurrency(paymentDetails?.vatAmount ?? 0)}
                          </span>
                        </div>
                      )}

                      <Separator />

                      <div className="flex justify-between text-lg font-semibold">
                        <span>Total Amount:</span>
                        <span>
                          {formatCurrency(paymentDetails?.totalAmount ?? 0)}
                        </span>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Payment Button */}
                {paymentDetails?.status !== Status.PAID &&
                  paymentDetails?.status !== Status.EXPIRED &&
                  paymentDetails?.paymentMethod === null && (
                    <div className="flex gap-2 pt-4">
                      <Button
                        variant="outline"
                        className="flex-1"
                        onClick={() => onClose()}
                        size="lg"
                      >
                        Cancel
                      </Button>
                      <Button
                        className="flex-1"
                        onClick={() => setShowPaymentForm(true)}
                        size="lg"
                      >
                        <CreditCard className="mr-2 size-4" />
                        Pay {formatCurrency(paymentDetails?.totalAmount ?? 0)}
                      </Button>
                    </div>
                  )}

                {/* comment section */}

                {paymentDetails?.status !== 'PAID' &&
                  paymentDetails?.paymentMethod !== null && (
                    <Card>
                      <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                          <MessageCircle className="size-4" />
                          Invoice Comments Logs
                        </CardTitle>
                        <CardDescription>
                          Track invoice status and add updates for the invoice.
                        </CardDescription>
                      </CardHeader>
                      <CardContent className="space-y-4">
                        {/* Comments History */}
                        <div className="max-h-[500px] overflow-y-auto">
                          <Card className="mt-4 p-4">
                            <div className="space-y-2">
                              {loadingComments ? (
                                <div className="flex h-full items-center justify-center">
                                  <p>Loading comments...</p>
                                </div>
                              ) : comments.length === 0 ? (
                                <div className="flex h-full items-center justify-center">
                                  <p>No comments found</p>
                                </div>
                              ) : (
                                comments.map((item, index) => (
                                  <div
                                    key={index}
                                    className={`${item.approved ? 'bg-primary/30' : 'bg-card-background'} rounded-md p-4`}
                                  >
                                    <div className="mb-3 flex items-start justify-between">
                                      <div className="flex items-center gap-3">
                                        <div className="flex size-8 items-center justify-center rounded-full bg-gradient-to-br from-primary to-primary/80 text-sm font-medium text-primary-foreground">
                                          {item.userName
                                            .split(' ')
                                            .map(n => n[0])
                                            .join('')}
                                        </div>
                                        <div>
                                          <div className="font-medium text-foreground">
                                            {item.userName}
                                          </div>
                                          <div className="text-xs text-muted-foreground">
                                            {humanizeText(item.userRole)}
                                          </div>
                                        </div>
                                      </div>
                                      <div className="text-xs text-muted-foreground">
                                        {formatDateTime(item.createdAt)}
                                      </div>
                                    </div>

                                    <p className="mb-3 text-sm text-foreground">
                                      {item.comment}
                                    </p>

                                    <div className="grid grid-cols-2 gap-3">
                                      <div>
                                        <div className="mb-1 text-xs font-medium text-muted-foreground">
                                          Action Taken
                                        </div>
                                        <div className="flex items-center gap-2">
                                          <ActionStatusIcon
                                            action={item.actionName}
                                          />
                                          <span className="text-sm text-foreground">
                                            {item.actionName}
                                          </span>
                                        </div>
                                      </div>
                                      <div>
                                        <div className="mb-1 text-xs font-medium text-muted-foreground">
                                          Next Step
                                        </div>
                                        <div className="text-sm text-foreground">
                                          {item.nextStepName}
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                ))
                              )}
                            </div>
                          </Card>
                        </div>
                        {/* Add Comment Section */}
                        {loadingComments ? (
                          <div className="flex h-full items-center justify-center">
                            <Loader2 className="size-4 animate-spin text-primary" />
                          </div>
                        ) : comments.filter(item => item.approved).length ===
                          0 ? (
                          <Card className="p-4">
                            <div className="space-y-4">
                              <div>
                                <Label htmlFor="comment">
                                  Comment{' '}
                                  <span className="text-destructive">*</span>
                                </Label>
                                <Textarea
                                  id="comment"
                                  value={comment}
                                  onChange={e => setComment(e.target.value)}
                                  placeholder="Add your comment here..."
                                  rows={3}
                                />
                              </div>

                              <div className="grid grid-cols-2 gap-4">
                                <div>
                                  <Label htmlFor="actionTaken">
                                    Action Taken{' '}
                                    <span className="text-destructive">*</span>
                                  </Label>
                                  <Select
                                    value={actionTaken}
                                    onValueChange={value =>
                                      setActionTaken(value)
                                    }
                                  >
                                    <SelectTrigger>
                                      <SelectValue placeholder="Select action taken" />
                                    </SelectTrigger>
                                    <SelectContent>
                                      {actionTakenOptions.map(option => (
                                        <SelectItem
                                          key={option.value}
                                          value={option.value}
                                        >
                                          {option.label}
                                        </SelectItem>
                                      ))}
                                    </SelectContent>
                                  </Select>
                                </div>

                                <div>
                                  <Label htmlFor="nextStep">
                                    Next Step{' '}
                                    <span className="text-destructive">*</span>
                                  </Label>
                                  <Select
                                    value={nextStep}
                                    onValueChange={value => setNextStep(value)}
                                  >
                                    <SelectTrigger>
                                      <SelectValue placeholder="Select next step" />
                                    </SelectTrigger>
                                    <SelectContent>
                                      {nextStepOptions.map(option => (
                                        <SelectItem
                                          key={option.value}
                                          value={option.value}
                                        >
                                          {option.label}
                                        </SelectItem>
                                      ))}
                                    </SelectContent>
                                  </Select>
                                </div>
                              </div>

                              {/* Action Buttons */}
                              <div className="flex justify-end gap-3 pt-2">
                                <Button
                                  variant="outline"
                                  onClick={onClose}
                                  size="sm"
                                >
                                  Cancel
                                </Button>
                                <Button
                                  onClick={handleSubmit}
                                  size="sm"
                                  disabled={commentSubmitting}
                                >
                                  {commentSubmitting ? (
                                    <div className="flex items-center gap-2">
                                      <div className="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                      Submitting...
                                    </div>
                                  ) : (
                                    <>
                                      <Send className="size-4" />
                                      Submit
                                    </>
                                  )}
                                </Button>
                              </div>
                            </div>
                          </Card>
                        ) : (
                          <div className="flex h-full items-center justify-center rounded-md bg-primary/10 p-4 text-primary">
                            <p>This invoice is already approved</p>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  )}
              </Fragment>
            )}
          </div>
        </DialogContent>
      </Dialog>

      <ClientPaymentModal
        open={showPaymentForm}
        onClose={() => setShowPaymentForm(false)}
        invoiceNo={paymentDetails?.id || ''}
        invoiceId={paymentDetails?.id || ''}
        data={paymentDetails}
        loading={paymentLoading}
        onPayment={handlePayment}
        onManualPaymentSuccess={() => {
          setShowPaymentForm(false);
          fetchPaymentDetails();
        }}
        totalAmount={paymentDetails?.totalAmount ?? 0}
      />
    </>
  );
};

export default InvoiceDetailsDialog;
