server:
  port: 8080

spring:
  application:
    name: jwt-current-context-demo
  data:
    mongodb:
      uri: mongodb://localhost:27017/context_demo
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: "change-this-demo-secret-key-change-this-demo-secret-key-123456"
    expiration-minutes: 60
