spring:
  config:
    import: "optional:classpath:common-defaults.yml,optional:classpath:common-defaults-prod.yml"
  application:
    name: cms-service
  leaderboard:
    api:
      url: "http://localhost:9090"
  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: cms

server:
  port: 5050

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=${AZURE_STORAGE_ACCOUNT_NAME};AccountKey=${AZURE_STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net
    container-name: strgblobstandardasatv2

web:
  client:
    base:
      #      url: http://localhost:5055/vps
      url: http://asat-vps-service:5052/vps

service:
  registration:
    url: ${REGISTRATION_SERVICE_URL:http://asat-registration-service:9090/registration/api/v1}
  billing:
    url: ${BILLING_SERVICE_URL:http://asat-billing-service:6060/billing/api/v1}

storage:
  active: s3
aws:
  region: us-east-1
  # From SSM: /asat/prod/cms-service/aws.credentials.access-key
  credentials:
    access-key: ${AWS_CREDENTIALS_ACCESS_KEY:}
    # From SSM: /asat/prod/cms-service/aws.credentials.secret-key
    secret-key: ${AWS_CREDENTIALS_SECRET_KEY:}

link:
  logo: https://aspiretss.s3.us-east-1.amazonaws.com/public/Image.png
  login: https://portal.securityawarenesstraining.ai/auth/login
  help: https://portal.securityawarenesstraining.ai/auth/login
  support-email: support@securityawarenesstraining.ai
