export interface ICoupon {
  id: string;
  name: string;
  description: string;
  code: string;
  autoGenerated: boolean;
  type: 'FIXED' | 'PERCENTAGE';
  value: number;
  currency: string;
  validFrom: string;
  validUntil: string;
  usageLimit: number;
  totalUsed: number;
  minPurchaseAmount: number;
  productRestrictions: [
    {
      productId: string;
      productName: string;
      packageId: string;
      packageName: string;
    },
  ];
  geographicRestrictions: string[];
  qrCodeUrl: string;
  urlCoupon: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  stackable: boolean;
  active: boolean;
}
