export interface INotification {
  id: string;
  userId: string;
  title: string;
  message: string;
  notificationType: NotificationType;
  metadata: string;
  createdAt: string;
  readAt: string;
  read: boolean;
}

export enum NotificationType {
  NEW_USER_REGISTERED = 'NEW_USER_REGISTERED',
  WELCOME_EMAIL = 'WELCOME_EMAIL',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_PASSWORD_CHANGE = 'USER_PASSWORD_CHANGE',
  USER_PASSWORD_CHANGE_ADMIN = 'USER_PASSWORD_CHANGE_ADMIN',
  BULK_USER_IMPORT_SUMMARY = 'BULK_USER_IMPORT_SUMMARY',
  NEW_COURSE_CREATED = 'NEW_COURSE_CREATED',
  COURSE_UPDATED = 'COURSE_UPDATED',
  COURSE_ASSIGNED = 'COURSE_ASSIGNED',
  COURSE_COMPLETION = 'COURSE_COMPLETION',
  NEW_PACKAGE_CREATED = 'NEW_PACKAGE_CREATED',
  PACKAGE_ASSIGNED = 'PACKAGE_ASSIGNED',
  PACKAGE_ASSIGNED_USER = 'PACKAGE_ASSIGNED_USER',
  PACKAGE_EXPIRY = 'PACKAGE_EXPIRY',
  CAMPAIGN_ACTIVITY = 'CAMPAIGN_ACTIVITY',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILURE = 'PAYMENT_FAILURE',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  NEW_POLICY_CREATED = 'NEW_POLICY_CREATED',
  POLICY_UPDATED = 'POLICY_UPDATED',
  POLICY_COMPLIANCE_REMINDER = 'POLICY_COMPLIANCE_REMINDER',
  CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
  CERTIFICATE_ISSUED_ADMIN = 'CERTIFICATE_ISSUED_ADMIN',
  LEADERBOARD_UPDATE = 'LEADERBOARD_UPDATE',
  CERTIFICATE_EXPIRY = 'CERTIFICATE_EXPIRY',
  CERTIFICATE_REVOKED = 'CERTIFICATE_REVOKED',
  SYSTEM_HEALTH_ALERTS = 'SYSTEM_HEALTH_ALERTS',
  SECURITY_ALERTS = 'SECURITY_ALERTS',
  UPDATES_PATCHES = 'UPDATES_PATCHES',
  FEATURE_UPDATE_CHANGE = 'FEATURE_UPDATE_CHANGE',
  REMINDER_PENDING_TASKS = 'REMINDER_PENDING_TASKS',
  SCHEDULED_MAINTENANCE = 'SCHEDULED_MAINTENANCE',
  HELP_DESK_TICKET_UPDATES = 'HELP_DESK_TICKET_UPDATES',
  SUBSCRIPTION_RENEWAL_REMINDER = 'SUBSCRIPTION_RENEWAL_REMINDER',
}
