plugins {
    id 'io.spring.dependency-management' version '1.1.5'
    id 'java'
    id 'jacoco'
}

group 'com.aspire.asat.billing'

dependencies {

    implementation project(':common:core')
    implementation project(':services:billing:api')
    implementation project.rootProject.ext.libraries.development.springDocUi

    implementation project.rootProject.ext.libraries.core.azureCosmos
    implementation project.rootProject.ext.libraries.core.lombok
    annotationProcessor project.rootProject.ext.libraries.core.lombok
    implementation project.rootProject.ext.libraries.core.springBootStarter
    implementation project.rootProject.ext.libraries.core.springBootStarterWeb
    implementation project.rootProject.ext.libraries.core.jacksonCore
    implementation project.rootProject.ext.libraries.core.jacksonDatatype
    implementation project.rootProject.ext.libraries.core.springBootStarterDataMongo
    implementation project.rootProject.ext.libraries.core.mockitoCore
    implementation project.rootProject.ext.libraries.core.blobStorage
    implementation project.rootProject.ext.libraries.core.commonsCsv
    implementation project.rootProject.ext.libraries.core.jwtApi
    implementation project.rootProject.ext.libraries.core.jwtImpl
    implementation project.rootProject.ext.libraries.core.jwtJackson
//    implementation project.rootProject.ext.libraries.core.validationApi
    implementation 'com.stripe:stripe-java:20.133.0'
    implementation 'com.paypal.sdk:checkout-sdk:2.0.0'
    implementation 'com.google.code.gson:gson:2.10.1' // or the latest version
    implementation 'com.itextpdf:itextpdf:5.5.13.3'
    implementation 'com.azure:azure-storage-blob:12.19.0'
    implementation 'com.google.zxing:core:3.5.2'
    implementation 'com.google.zxing:javase:3.5.2'
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation
    implementation("org.springframework.boot:spring-boot-starter-validation:3.4.4")
    implementation project.rootProject.ext.libraries.core.aspectjweaver
    implementation project.rootProject.ext.libraries.core.openhtmltopdf
    implementation project.rootProject.ext.libraries.core.jsoup
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.0.6'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    implementation project.rootProject.ext.libraries.core.awsSdkS3

    testImplementation sourceSets.main.output
    testImplementation project.rootProject.ext.libraries.test.mockitoJunitJupiter
    testImplementation platform(project.rootProject.ext.libraries.test.junitBom)
    testImplementation project.rootProject.ext.libraries.test.junitJupiter
    testRuntimeOnly project.rootProject.ext.libraries.test.junitPlatformLauncher
    testImplementation project.rootProject.ext.libraries.test.testcontainers
    testImplementation project.rootProject.ext.libraries.test.testcontainersJunit
    testImplementation project.rootProject.ext.libraries.test.testcontainersMongodb
    testAnnotationProcessor project.rootProject.ext.libraries.core.lombok

}

tasks.named('compileTestJava') {
    dependsOn(tasks.named('classes'))
}

tasks.withType(JavaCompile) {
    options.compilerArgs << "-parameters"
}

jacoco {
    toolVersion = project.rootProject.ext.versions.test.jacoco
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
        csv.required = true
    }
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.80
            }
        }
    }
}

tasks.test {
    useJUnitPlatform()
}
